// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: play.proto

package play

import (
	core "gitee.com/orbit-w/orbit/pkg/proto/core"
	mme "gitee.com/orbit-w/orbit/pkg/proto/mme"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_play_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_play_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_play_proto_rawDescGZIP(), []int{0}
}

type Request_LoginRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerEntityRef *mme.EntityRef         `protobuf:"bytes,1,opt,name=PlayerEntityRef,proto3,oneof" json:"PlayerEntityRef,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request_LoginRequest) Reset() {
	*x = Request_LoginRequest{}
	mi := &file_play_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_LoginRequest) ProtoMessage() {}

func (x *Request_LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_play_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_LoginRequest.ProtoReflect.Descriptor instead.
func (*Request_LoginRequest) Descriptor() ([]byte, []int) {
	return file_play_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_LoginRequest) GetPlayerEntityRef() *mme.EntityRef {
	if x != nil {
		return x.PlayerEntityRef
	}
	return nil
}

type Request_LoginRequest_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *core.Error            `protobuf:"bytes,1,opt,name=Error,proto3,oneof" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_LoginRequest_Rsp) Reset() {
	*x = Request_LoginRequest_Rsp{}
	mi := &file_play_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_LoginRequest_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_LoginRequest_Rsp) ProtoMessage() {}

func (x *Request_LoginRequest_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_play_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_LoginRequest_Rsp.ProtoReflect.Descriptor instead.
func (*Request_LoginRequest_Rsp) Descriptor() ([]byte, []int) {
	return file_play_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_LoginRequest_Rsp) GetError() *core.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_play_proto protoreflect.FileDescriptor

const file_play_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"play.proto\x12\x04Play\x1a\fcommon.proto\x1a\n" +
	"core.proto\"\xa6\x01\n" +
	"\aRequest\x1a\x9a\x01\n" +
	"\fLoginRequest\x12=\n" +
	"\x0fPlayerEntityRef\x18\x01 \x01(\v2\x0e.MME.EntityRefH\x00R\x0fPlayerEntityRef\x88\x01\x01\x1a7\n" +
	"\x03Rsp\x12&\n" +
	"\x05Error\x18\x01 \x01(\v2\v.Core.ErrorH\x00R\x05Error\x88\x01\x01B\b\n" +
	"\x06_ErrorB\x12\n" +
	"\x10_PlayerEntityRefB(Z&gitee.com/orbit-w/orbit/pkg/proto/playb\x06proto3"

var (
	file_play_proto_rawDescOnce sync.Once
	file_play_proto_rawDescData []byte
)

func file_play_proto_rawDescGZIP() []byte {
	file_play_proto_rawDescOnce.Do(func() {
		file_play_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_play_proto_rawDesc), len(file_play_proto_rawDesc)))
	})
	return file_play_proto_rawDescData
}

var file_play_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_play_proto_goTypes = []any{
	(*Request)(nil),                  // 0: Play.Request
	(*Request_LoginRequest)(nil),     // 1: Play.Request.LoginRequest
	(*Request_LoginRequest_Rsp)(nil), // 2: Play.Request.LoginRequest.Rsp
	(*mme.EntityRef)(nil),            // 3: MME.EntityRef
	(*core.Error)(nil),               // 4: Core.Error
}
var file_play_proto_depIdxs = []int32{
	3, // 0: Play.Request.LoginRequest.PlayerEntityRef:type_name -> MME.EntityRef
	4, // 1: Play.Request.LoginRequest.Rsp.Error:type_name -> Core.Error
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_play_proto_init() }
func file_play_proto_init() {
	if File_play_proto != nil {
		return
	}
	file_play_proto_msgTypes[1].OneofWrappers = []any{}
	file_play_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_play_proto_rawDesc), len(file_play_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_play_proto_goTypes,
		DependencyIndexes: file_play_proto_depIdxs,
		MessageInfos:      file_play_proto_msgTypes,
	}.Build()
	File_play_proto = out.File
	file_play_proto_goTypes = nil
	file_play_proto_depIdxs = nil
}
