// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: app/proto/messages.proto

// 定义RPC通信协议包名

package messages

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPC请求消息定义
// 用于客户端向服务端发送RPC调用请求
type RpcHelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发送者进程ID，用于服务端回复消息
	Sender        *actor.PID `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcHelloRequest) Reset() {
	*x = RpcHelloRequest{}
	mi := &file_app_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHelloRequest) ProtoMessage() {}

func (x *RpcHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHelloRequest.ProtoReflect.Descriptor instead.
func (*RpcHelloRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHelloRequest) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

// RPC响应消息定义
// 用于服务端向客户端返回RPC调用结果
type RpcHelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应消息内容
	Message       string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcHelloResponse) Reset() {
	*x = RpcHelloResponse{}
	mi := &file_app_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHelloResponse) ProtoMessage() {}

func (x *RpcHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHelloResponse.ProtoReflect.Descriptor instead.
func (*RpcHelloResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RpcHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_proto_messages_proto protoreflect.FileDescriptor

var file_app_proto_messages_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x1a, 0x0b, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x35, 0x0a, 0x0f, 0x52, 0x70, 0x63, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x70, 0x63, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_proto_messages_proto_rawDescOnce sync.Once
	file_app_proto_messages_proto_rawDescData []byte
)

func file_app_proto_messages_proto_rawDescGZIP() []byte {
	file_app_proto_messages_proto_rawDescOnce.Do(func() {
		file_app_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_messages_proto_rawDesc), len(file_app_proto_messages_proto_rawDesc)))
	})
	return file_app_proto_messages_proto_rawDescData
}

var file_app_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_proto_messages_proto_goTypes = []any{
	(*RpcHelloRequest)(nil),  // 0: messages.RpcHelloRequest
	(*RpcHelloResponse)(nil), // 1: messages.RpcHelloResponse
	(*actor.PID)(nil),        // 2: actor.PID
}
var file_app_proto_messages_proto_depIdxs = []int32{
	2, // 0: messages.RpcHelloRequest.Sender:type_name -> actor.PID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_proto_messages_proto_init() }
func file_app_proto_messages_proto_init() {
	if File_app_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_messages_proto_rawDesc), len(file_app_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_messages_proto_goTypes,
		DependencyIndexes: file_app_proto_messages_proto_depIdxs,
		MessageInfos:      file_app_proto_messages_proto_msgTypes,
	}.Build()
	File_app_proto_messages_proto = out.File
	file_app_proto_messages_proto_goTypes = nil
	file_app_proto_messages_proto_depIdxs = nil
}
