// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: app/proto/season.proto

package pb_season

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_app_proto_season_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_season_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_app_proto_season_proto_rawDescGZIP(), []int{0}
}

type Request_SeasonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SeasonInfo) Reset() {
	*x = Request_SeasonInfo{}
	mi := &file_app_proto_season_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SeasonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SeasonInfo) ProtoMessage() {}

func (x *Request_SeasonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_season_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SeasonInfo.ProtoReflect.Descriptor instead.
func (*Request_SeasonInfo) Descriptor() ([]byte, []int) {
	return file_app_proto_season_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_SeasonInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request_SeasonInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Request_SeasonInfo_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SeasonInfo_Rsp) Reset() {
	*x = Request_SeasonInfo_Rsp{}
	mi := &file_app_proto_season_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SeasonInfo_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SeasonInfo_Rsp) ProtoMessage() {}

func (x *Request_SeasonInfo_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_season_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SeasonInfo_Rsp.ProtoReflect.Descriptor instead.
func (*Request_SeasonInfo_Rsp) Descriptor() ([]byte, []int) {
	return file_app_proto_season_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_SeasonInfo_Rsp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_app_proto_season_proto protoreflect.FileDescriptor

var file_app_proto_season_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x66, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x5b, 0x0a, 0x0a, 0x53,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1d, 0x0a, 0x03, 0x52, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x62, 0x2f, 0x70,
	0x62, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_proto_season_proto_rawDescOnce sync.Once
	file_app_proto_season_proto_rawDescData []byte
)

func file_app_proto_season_proto_rawDescGZIP() []byte {
	file_app_proto_season_proto_rawDescOnce.Do(func() {
		file_app_proto_season_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_season_proto_rawDesc), len(file_app_proto_season_proto_rawDesc)))
	})
	return file_app_proto_season_proto_rawDescData
}

var file_app_proto_season_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_proto_season_proto_goTypes = []any{
	(*Request)(nil),                // 0: Season.Request
	(*Request_SeasonInfo)(nil),     // 1: Season.Request.SeasonInfo
	(*Request_SeasonInfo_Rsp)(nil), // 2: Season.Request.SeasonInfo.Rsp
}
var file_app_proto_season_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_proto_season_proto_init() }
func file_app_proto_season_proto_init() {
	if File_app_proto_season_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_season_proto_rawDesc), len(file_app_proto_season_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_season_proto_goTypes,
		DependencyIndexes: file_app_proto_season_proto_depIdxs,
		MessageInfos:      file_app_proto_season_proto_msgTypes,
	}.Build()
	File_app_proto_season_proto = out.File
	file_app_proto_season_proto_goTypes = nil
	file_app_proto_season_proto_depIdxs = nil
}
