// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: season.proto

package pb_season

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_season_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_season_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_season_proto_rawDescGZIP(), []int{0}
}

type Request_SeasonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SeasonInfo) Reset() {
	*x = Request_SeasonInfo{}
	mi := &file_season_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SeasonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SeasonInfo) ProtoMessage() {}

func (x *Request_SeasonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_season_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SeasonInfo.ProtoReflect.Descriptor instead.
func (*Request_SeasonInfo) Descriptor() ([]byte, []int) {
	return file_season_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_SeasonInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request_SeasonInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Request_SeasonInfo_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SeasonInfo_Rsp) Reset() {
	*x = Request_SeasonInfo_Rsp{}
	mi := &file_season_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SeasonInfo_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SeasonInfo_Rsp) ProtoMessage() {}

func (x *Request_SeasonInfo_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_season_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SeasonInfo_Rsp.ProtoReflect.Descriptor instead.
func (*Request_SeasonInfo_Rsp) Descriptor() ([]byte, []int) {
	return file_season_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_SeasonInfo_Rsp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_season_proto protoreflect.FileDescriptor

const file_season_proto_rawDesc = "" +
	"\n" +
	"\fseason.proto\x12\x06Season\"f\n" +
	"\aRequest\x1a[\n" +
	"\n" +
	"SeasonInfo\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bDuration\x18\x02 \x01(\x05R\bDuration\x1a\x1d\n" +
	"\x03Rsp\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06ResultB\x0eZ\fpb/pb_seasonb\x06proto3"

var (
	file_season_proto_rawDescOnce sync.Once
	file_season_proto_rawDescData []byte
)

func file_season_proto_rawDescGZIP() []byte {
	file_season_proto_rawDescOnce.Do(func() {
		file_season_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_season_proto_rawDesc), len(file_season_proto_rawDesc)))
	})
	return file_season_proto_rawDescData
}

var file_season_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_season_proto_goTypes = []any{
	(*Request)(nil),                // 0: Season.Request
	(*Request_SeasonInfo)(nil),     // 1: Season.Request.SeasonInfo
	(*Request_SeasonInfo_Rsp)(nil), // 2: Season.Request.SeasonInfo.Rsp
}
var file_season_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_season_proto_init() }
func file_season_proto_init() {
	if File_season_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_season_proto_rawDesc), len(file_season_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_season_proto_goTypes,
		DependencyIndexes: file_season_proto_depIdxs,
		MessageInfos:      file_season_proto_msgTypes,
	}.Build()
	File_season_proto = out.File
	file_season_proto_goTypes = nil
	file_season_proto_depIdxs = nil
}
