// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: meta.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatcherType int32

const (
	DispatcherType_DISPATCHER_TYPE_IN_WORLD  DispatcherType = 0 // 世界分组
	DispatcherType_DISPATCHER_TYPE_IN_REGION DispatcherType = 1 // 区域分组
	DispatcherType_DISPATCHER_TYPE_RANDOM    DispatcherType = 2 // 随机分组
)

// Enum value maps for DispatcherType.
var (
	DispatcherType_name = map[int32]string{
		0: "DISPATCHER_TYPE_IN_WORLD",
		1: "DISPATCHER_TYPE_IN_REGION",
		2: "DISPATCHER_TYPE_RANDOM",
	}
	DispatcherType_value = map[string]int32{
		"DISPATCHER_TYPE_IN_WORLD":  0,
		"DISPATCHER_TYPE_IN_REGION": 1,
		"DISPATCHER_TYPE_RANDOM":    2,
	}
)

func (x DispatcherType) Enum() *DispatcherType {
	p := new(DispatcherType)
	*p = x
	return p
}

func (x DispatcherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatcherType) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_proto_enumTypes[0].Descriptor()
}

func (DispatcherType) Type() protoreflect.EnumType {
	return &file_meta_proto_enumTypes[0]
}

func (x DispatcherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatcherType.Descriptor instead.
func (DispatcherType) EnumDescriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorName     string                 `protobuf:"bytes,1,opt,name=ActorName,proto3" json:"ActorName,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=ServerId,proto3" json:"ServerId,omitempty"` //初始逻辑服ID
	Dispatcher    *Dispatcher            `protobuf:"bytes,4,opt,name=Dispatcher,proto3" json:"Dispatcher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *Meta) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Meta) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Meta) GetDispatcher() *Dispatcher {
	if x != nil {
		return x.Dispatcher
	}
	return nil
}

type Dispatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DispatcherType         `protobuf:"varint,1,opt,name=Type,proto3,enum=meta.DispatcherType" json:"Type,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=ServerId,proto3" json:"ServerId,omitempty"` //最新的逻辑服ID
	NodeId        string                 `protobuf:"bytes,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`     //最新的节点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dispatcher) Reset() {
	*x = Dispatcher{}
	mi := &file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatcher) ProtoMessage() {}

func (x *Dispatcher) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatcher.ProtoReflect.Descriptor instead.
func (*Dispatcher) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *Dispatcher) GetType() DispatcherType {
	if x != nil {
		return x.Type
	}
	return DispatcherType_DISPATCHER_TYPE_IN_WORLD
}

func (x *Dispatcher) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Dispatcher) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_meta_proto protoreflect.FileDescriptor

const file_meta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"meta.proto\x12\x04meta\"\x8c\x01\n" +
	"\x04Meta\x12\x1c\n" +
	"\tActorName\x18\x01 \x01(\tR\tActorName\x12\x18\n" +
	"\aPattern\x18\x02 \x01(\tR\aPattern\x12\x1a\n" +
	"\bServerId\x18\x03 \x01(\tR\bServerId\x120\n" +
	"\n" +
	"Dispatcher\x18\x04 \x01(\v2\x10.meta.DispatcherR\n" +
	"Dispatcher\"j\n" +
	"\n" +
	"Dispatcher\x12(\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x14.meta.DispatcherTypeR\x04Type\x12\x1a\n" +
	"\bServerId\x18\x02 \x01(\tR\bServerId\x12\x16\n" +
	"\x06NodeId\x18\x03 \x01(\tR\x06NodeId*i\n" +
	"\x0eDispatcherType\x12\x1c\n" +
	"\x18DISPATCHER_TYPE_IN_WORLD\x10\x00\x12\x1d\n" +
	"\x19DISPATCHER_TYPE_IN_REGION\x10\x01\x12\x1a\n" +
	"\x16DISPATCHER_TYPE_RANDOM\x10\x02B\bZ\x06.;metab\x06proto3"

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_proto_goTypes = []any{
	(DispatcherType)(0), // 0: meta.DispatcherType
	(*Meta)(nil),        // 1: meta.Meta
	(*Dispatcher)(nil),  // 2: meta.Dispatcher
}
var file_meta_proto_depIdxs = []int32{
	2, // 0: meta.Meta.Dispatcher:type_name -> meta.Dispatcher
	0, // 1: meta.Dispatcher.Type:type_name -> meta.DispatcherType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		EnumInfos:         file_meta_proto_enumTypes,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
