// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: meta.proto

package zone_meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zone_DispatcherType int32

const (
	Zone_DispatcherType_ForWorld      Zone_DispatcherType = 0 // 世界分组
	Zone_DispatcherType_ForDesignated Zone_DispatcherType = 1 // 指定节点服分组
	Zone_DispatcherType_ForRandom     Zone_DispatcherType = 2 // 随机服分组
)

// Enum value maps for Zone_DispatcherType.
var (
	Zone_DispatcherType_name = map[int32]string{
		0: "ForWorld",
		1: "ForDesignated",
		2: "ForRandom",
	}
	Zone_DispatcherType_value = map[string]int32{
		"ForWorld":      0,
		"ForDesignated": 1,
		"ForRandom":     2,
	}
)

func (x Zone_DispatcherType) Enum() *Zone_DispatcherType {
	p := new(Zone_DispatcherType)
	*p = x
	return p
}

func (x Zone_DispatcherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Zone_DispatcherType) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_proto_enumTypes[0].Descriptor()
}

func (Zone_DispatcherType) Type() protoreflect.EnumType {
	return &file_meta_proto_enumTypes[0]
}

func (x Zone_DispatcherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Zone_DispatcherType.Descriptor instead.
func (Zone_DispatcherType) EnumDescriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

type ZoneMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Pattern       int32                  `protobuf:"varint,2,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	Dispatcher    *ZoneDispatcher        `protobuf:"bytes,3,opt,name=Dispatcher,proto3" json:"Dispatcher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneMeta) Reset() {
	*x = ZoneMeta{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneMeta) ProtoMessage() {}

func (x *ZoneMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneMeta.ProtoReflect.Descriptor instead.
func (*ZoneMeta) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ZoneMeta) GetPattern() int32 {
	if x != nil {
		return x.Pattern
	}
	return 0
}

func (x *ZoneMeta) GetDispatcher() *ZoneDispatcher {
	if x != nil {
		return x.Dispatcher
	}
	return nil
}

type ZoneDispatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Zone_DispatcherType    `protobuf:"varint,1,opt,name=Type,proto3,enum=zone_meta.Zone_DispatcherType" json:"Type,omitempty"`
	ServerId      int32                  `protobuf:"varint,2,opt,name=ServerId,proto3" json:"ServerId,omitempty"` //最新的逻辑服ID
	NodeId        string                 `protobuf:"bytes,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`      //最新的节点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneDispatcher) Reset() {
	*x = ZoneDispatcher{}
	mi := &file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneDispatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneDispatcher) ProtoMessage() {}

func (x *ZoneDispatcher) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneDispatcher.ProtoReflect.Descriptor instead.
func (*ZoneDispatcher) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneDispatcher) GetType() Zone_DispatcherType {
	if x != nil {
		return x.Type
	}
	return Zone_DispatcherType_ForWorld
}

func (x *ZoneDispatcher) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ZoneDispatcher) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_meta_proto protoreflect.FileDescriptor

const file_meta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"meta.proto\x12\tzone_meta\"o\n" +
	"\bZoneMeta\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x18\n" +
	"\aPattern\x18\x02 \x01(\x05R\aPattern\x129\n" +
	"\n" +
	"Dispatcher\x18\x03 \x01(\v2\x19.zone_meta.ZoneDispatcherR\n" +
	"Dispatcher\"x\n" +
	"\x0eZoneDispatcher\x122\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1e.zone_meta.Zone_DispatcherTypeR\x04Type\x12\x1a\n" +
	"\bServerId\x18\x02 \x01(\x05R\bServerId\x12\x16\n" +
	"\x06NodeId\x18\x03 \x01(\tR\x06NodeId*E\n" +
	"\x13Zone_DispatcherType\x12\f\n" +
	"\bForWorld\x10\x00\x12\x11\n" +
	"\rForDesignated\x10\x01\x12\r\n" +
	"\tForRandom\x10\x02B\rZ\v.;zone_metab\x06proto3"

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_proto_goTypes = []any{
	(Zone_DispatcherType)(0), // 0: zone_meta.Zone_DispatcherType
	(*ZoneMeta)(nil),         // 1: zone_meta.ZoneMeta
	(*ZoneDispatcher)(nil),   // 2: zone_meta.ZoneDispatcher
}
var file_meta_proto_depIdxs = []int32{
	2, // 0: zone_meta.ZoneMeta.Dispatcher:type_name -> zone_meta.ZoneDispatcher
	0, // 1: zone_meta.ZoneDispatcher.Type:type_name -> zone_meta.Zone_DispatcherType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		EnumInfos:         file_meta_proto_enumTypes,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
