// Code generated by routergen. DO NOT EDIT.
// This file is automatically generated from NetWall YAML files.
// To regenerate, run: go generate or blueprintgen.

package controllerv2

import (
	agent "gitee.com/orbit-w/orbit/internal/game/mme_agent"
	"gitee.com/orbit-w/orbit/pkg/proto/core"
	"gitee.com/orbit-w/orbit/pkg/proto/mme"
	"gitee.com/orbit-w/orbit/pkg/proto/play"
	"google.golang.org/protobuf/proto"
)

var (
	GControllerV2 = &Controller{}
)

type Controller struct{}

func (c *Controller) HandleHeartBeat(req *core.Request_HeartBeat) proto.Message {
	// TODO: 实现业务逻辑
	return nil
}

func (c *Controller) HandleSetEntityRequest(req *core.Request_SetEntityRequest) proto.Message {
	// TODO: 实现业务逻辑
	return nil
}

func (c *Controller) HandleAskLevelUp(req *mme.Request_AskLevelUp) proto.Message {
	// TODO: 实现业务逻辑
	return nil
}

func (c *Controller) HandleLoginRequest(req *play.Request_LoginRequest, playerEntity *agent.PlayerEntityImpl) proto.Message {
	// TODO: 实现业务逻辑
	// playerEntity 已经由 Router 层加载完成，可以直接使用
	return nil
}
