// Code generated by routergen. DO NOT EDIT.
// This file is automatically generated from NetWall YAML files.
// To regenerate, run: go generate or blueprintgen.

package controllerv2

import (
	"gitee.com/orbit-w/meteor/modules/mlog"
	mmeobj "gitee.com/orbit-w/orbit/internal/game/mme"
	"go.uber.org/zap"

	"gitee.com/orbit-w/orbit/pkg/proto/core"
	"gitee.com/orbit-w/orbit/pkg/proto/mme"
	"gitee.com/orbit-w/orbit/pkg/proto/sample"
	"google.golang.org/protobuf/proto"
)

var (
	GControllerV2 = &Controller{}
)

type Controller struct{}

func (c *Controller) HandleSearchBook(req *core.Request_SearchBook) proto.Message {
	// TODO: 实现业务逻辑
	mlog.Info("HandleSearchBook", zap.Any("req", req))
	return &core.Request_SearchBook_Rsp{
		Result: &core.Book{
			Content: proto.String("Hello, World!"),
		},
	}
}

func (c *Controller) HandleHeartBeat(req *core.Request_HeartBeat) proto.Message {
	// TODO: 实现业务逻辑
	mlog.Info("HandleHeartBeat", zap.Any("req", req))
	return &core.OK{}
}

func (c *Controller) HandleAskLevelUp(req *mme.Request_AskLevelUp) proto.Message {
	// TODO: 实现业务逻辑
	return nil
}

func (c *Controller) HandleSearchNewsPaper(req *sample.Request_SearchNewsPaper) proto.Message {
	// TODO: 实现业务逻辑
	return nil
}

func (c *Controller) HandleLoginRequest(req *core.Request_LoginRequest, playerEntity *mmeobj.PlayerEntityWrapper) proto.Message {
	// TODO: 实现业务逻辑
	// playerEntity 已经由 Router 层加载完成，可以直接使用
	return nil
}

func (c *Controller) HandleSetEntityRequest(req *core.Request_SetEntityRequest) proto.Message {
	// TODO: 实现业务逻辑
	return nil
}
