syntax = "proto3";

package mechanisms;
option go_package = "./mme";

import "protocol/common.proto";

// 升级机制
message LevelUpMechanism {
  optional int64 Id = 1;         // 升级实例唯一Id
  optional int32 CurLevel = 2;  // 当前等级
  optional int32 CurExp = 3;    // 当前经验值
  optional int32 ConfId = 4;    // 走哪套升级配置

  int32 XXXId = 10000; // 自动化生成MechanismId，范式，不可修改。
}

// 英雄机制
// XXXId 是根据HeroMechanism结构体中Id字段自动化生成的，用于记录英雄实例唯一Id。结构模式固定，不要修改。
message HeroMechanism {
  optional int64 Id = 1;         // 英雄实例唯一Id
  optional int32 ConfId = 2;     // 英雄配置ID
  optional int64 CreateTime = 3; // 玩家获得英雄的时间
  optional int32 UseTimes = 4;   // 英雄被使用次数
  map<int32, int32> Skills = 5; // 技能

  repeated SkillXXXChange SkillChanges = 1005; // 技能变化

  int32 XXXId = 10000; // 自动化生成MechanismId，范式，不可修改。
}

//XXXChange 是根据HeroMechanism结构体中Skills字段自动化生成的，用于记录技能变化。结构模式固定，不要修改。
message SkillXXXChange {
  common.ChangeType ChangeType = 1;
  int32 Key = 2;
  int32 Value = 3; 
}

// 手动解锁机制
message ManualUnlockMechanism {
  map<int32, bool> UnlockMap = 1;  // 解锁状态

  int32 XXXId = 10000; // 自动化生成MechanismId，范式，不可修改。
}

// 穿戴机制
message WearMechanism {
  map<int32, int32> WearMap = 1;  // 穿戴状态
  optional int32 ConfId = 2;               // 走哪套穿戴配置

  int32 XXXId = 10000; // 自动化生成MechanismId，范式，不可修改。
}
