syntax = "proto3";

package MME;
option go_package = "./mme";

message LevelUpMechanism {
    optional int32 CurLevel = 1;
    optional int32 CurExp = 2;
    optional int32 ConfId = 3;
}

message HeroMechanism {
    optional int64 Id = 1;
    optional int32 ConfId = 2;
    optional int64 CreateTime = 3;
    optional int32 UseTimes = 4;
    map<int32, int32> Skills = 5;
    repeated Skills_XXXMapChangeRecord Skills_XXXChangeList = 1005;  message Skills_XXXMapChangeRecord { int32 Key = 1; int32 Value = 2; bool IsDelete = 3; }
}

message ManualUnlockMechanism {
    map<int32, bool> UnlockMap = 1;
}

message WearMechanism {
    map<int32, int32> WearMap = 1;
    optional int32 ConfId = 2;
}

