syntax = "proto3";

package mechanisms;
option go_package = "./mme";

import "protocol/common.proto";

// 升级机制
message LevelUpMechanism {
  optional int32 CurLevel = 1;  // 当前等级
  optional int32 CurExp = 2;    // 当前经验值
  optional int32 ConfId = 3;    // 走哪套升级配置
}

// 升级机制设置
message LevelUpMechanismSettings {
  optional bool AutoLevelUp = 1;  // 经验够则自动升级
}

// 英雄机制
message HeroMechanism {
  optional int64 Id = 1;         // 英雄实例唯一Id
  optional int32 ConfId = 2;     // 英雄配置ID
  optional int64 CreateTime = 3; // 玩家获得英雄的时间
  optional int32 UseTimes = 4;   // 英雄被使用次数
  map<int32, int32> Skills = 5; // 技能

  repeated SkillXXXChange SkillChanges = 1005; // 技能变化
}

//XXXChange 是根据HeroMechanism结构体中Skills字段自动化生成的，用于记录技能变化。结构模式固定，不要修改。
message SkillXXXChange {
  common.ChangeType ChangeType = 1;
  int32 Key = 2;
  optional int32 Value = 3; 
}

// 手动解锁机制
message ManualUnlockMechanism {
  map<int32, bool> UnlockMap = 1;  // 解锁状态
}

// 穿戴机制
message WearMechanism {
  map<int32, int32> WearMap = 1;  // 穿戴状态
  optional int32 ConfId = 2;               // 走哪套穿戴配置
}
