// Code generated by genproto. DO NOT EDIT.
package pb

import (
	"fmt"
	"google.golang.org/protobuf/proto"
	"github.com/orbit-w/orbit/app/proto/pb/pb_core"
)

// ParseCoreNotifyByID 根据协议ID解析通知消息
func ParseCoreNotifyByID(pid uint32, data []byte) (proto.Message, uint32, error) {
	switch pid {
	case PID_Core_Notify_BeAttacked: // Notify_BeAttacked
		notify := &pb_core.Notify_BeAttacked{}
		if err := proto.Unmarshal(data, notify); err != nil {
			return nil, 0, fmt.Errorf("unmarshal Notify_BeAttacked failed: %w", err)
		}
		return notify, pid, nil
	default:
		return nil, 0, fmt.Errorf("unknown notify protocol ID: 0x%08x", pid)
	}
}

// MarshalBeAttacked 序列化BeAttacked通知消息
func MarshalBeAttacked(notify *pb_core.Notify_BeAttacked) ([]byte, uint32, error) {
	data, err := proto.Marshal(notify)
	return data, PID_Core_Notify_BeAttacked, err
}

