// Code generated by protocol ID generator. DO NOT EDIT.
package pb

// Protocol IDs for Core package messages
const (
	PID_Core_BeAttacked uint32 = 0xfc87b763 // Core.BeAttacked
	PID_Core_Book uint32 = 0x2208a5d5 // Core.Book
	PID_Core_Error uint32 = 0x25d988c4 // Core.Error
	PID_Core_HeartBeat uint32 = 0x54294753 // Core.HeartBeat
	PID_Core_Notify uint32 = 0x6b7711d3 // Core.Notify
	PID_Core_OK uint32 = 0x65732552 // Core.OK
	PID_Core_Request uint32 = 0x518423f0 // Core.Request
	PID_Core_Rsp uint32 = 0xa23a6aad // Core.Rsp
	PID_Core_SearchBook uint32 = 0x10de33b7 // Core.SearchBook
)

// MessageNameToID maps message names to their protocol IDs
var CoreMessageNameToID = map[string]uint32{
	"BeAttacked": PID_Core_BeAttacked,
	"Book": PID_Core_Book,
	"Error": PID_Core_Error,
	"HeartBeat": PID_Core_HeartBeat,
	"Notify": PID_Core_Notify,
	"OK": PID_Core_OK,
	"Request": PID_Core_Request,
	"Rsp": PID_Core_Rsp,
	"SearchBook": PID_Core_SearchBook,
}

// GetProtocolID returns the protocol ID for the given message name
func GetCoreProtocolID(messageName string) (uint32, bool) {
	id, ok := CoreMessageNameToID[messageName]
	return id, ok
}
