// Code generated by genproto. DO NOT EDIT.
package pb

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
)

// ParseNotifyByID 根据协议ID解析通知消息
func ParseNotifyByID(pid uint32, data []byte) (proto.Message, uint32, error) {
	switch pid {
	case PID_Notify_BeAttacked: // Notify_BeAttacked
		notify := &Notify_BeAttacked{}
		if err := proto.Unmarshal(data, notify); err != nil {
			return nil, 0, fmt.Errorf("unmarshal Notify_BeAttacked failed: %w", err)
		}
		return notify, pid, nil
	default:
		return nil, 0, fmt.Errorf("unknown notify protocol ID: 0x%08x", pid)
	}
}

// MarshalBeAttacked 序列化BeAttacked通知消息
func MarshalBeAttacked(notify *Notify_BeAttacked) ([]byte, uint32, error) {
	data, err := proto.Marshal(notify)
	return data, PID_Notify_BeAttacked, err
}

