// Code generated by protocol ID generator. DO NOT EDIT.
package pb

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
	"gitee.com/orbit-w/orbit/lib/utils/proto_utils"
)

// 所有协议ID常量
const (
	PID_Notify_BeAttacked uint32 = 0x63a16597 // Notify_BeAttacked

)

// AllMessageNameToID 全局消息名称到ID的映射
var AllMessageNameToID = map[string]uint32{
	"Notify_BeAttacked": PID_Notify_BeAttacked,
}

// AllIDToMessageName 全局ID到消息名称的映射
var AllIDToMessageName = map[uint32]string{
	PID_Notify_BeAttacked: "Notify_BeAttacked",
}

// MessagePackageMap 消息名称到包名的映射
var MessagePackageMap = map[string]string{
	"Notify_BeAttacked": "Notify_BeAttacked",
}

// GetProtocolID 获取指定消息名称的协议ID
func GetProtocolID(messageName string) (uint32, bool) {
	id, ok := AllMessageNameToID[messageName]
	return id, ok
}

// GetMessageName 获取指定协议ID的消息名称
func GetMessageName(pid uint32) (string, bool) {
	name, ok := AllIDToMessageName[pid]
	return name, ok
}

// GetResponsePID 获取响应消息的协议ID
func GetResponsePID(response proto.Message) uint32 {
	if response == nil {
		return 0
	}

	messageName := proto_utils.ParseMessageName(response)
	if messageName == "" {
		return 0
	}

	// 从映射表中查找包名
	packageName, ok := MessagePackageMap[messageName]
	if !ok {
		// 找不到包名直接panic
		panic(fmt.Sprintf("消息 %s 未在映射表中找到对应的包名", messageName))
	}

	fullName := packageName + "-" + messageName
	pid, _ := GetProtocolID(fullName)
	return pid
}
