// Code generated by protocol ID generator. DO NOT EDIT.
package pb

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
	"gitee.com/orbit-w/orbit/lib/utils/proto_utils"
)

// 所有协议ID常量
const (
	PID_Notify_BeAttacked uint32 = 0x63a16597 // Notify_BeAttacked
	PID_Request_HeartBeat uint32 = 0x751e20c7 // Request_HeartBeat
	PID_Request_SearchBook uint32 = 0x73601d6f // Request_SearchBook
	PID_Request_SearchBook_Rsp uint32 = 0x7c102692 // Request_SearchBook_Rsp
	PID_Rsp_OK uint32 = 0x76d2290e // Rsp_OK
	PID_Rsp_Fail uint32 = 0x52833174 // Rsp_Fail

)

// AllMessageNameToID 全局消息名称到ID的映射
var AllMessageNameToID = map[string]uint32{
	"Notify_BeAttacked": PID_Notify_BeAttacked,
	"Request_HeartBeat": PID_Request_HeartBeat,
	"Request_SearchBook": PID_Request_SearchBook,
	"Request_SearchBook_Rsp": PID_Request_SearchBook_Rsp,
	"Rsp_OK": PID_Rsp_OK,
	"Rsp_Fail": PID_Rsp_Fail,
}

// AllIDToMessageName 全局ID到消息名称的映射
var AllIDToMessageName = map[uint32]string{
	PID_Notify_BeAttacked: "Notify_BeAttacked",
	PID_Request_HeartBeat: "Request_HeartBeat",
	PID_Request_SearchBook: "Request_SearchBook",
	PID_Request_SearchBook_Rsp: "Request_SearchBook_Rsp",
	PID_Rsp_OK: "Rsp_OK",
	PID_Rsp_Fail: "Rsp_Fail",
}

// GetProtocolID 获取指定消息名称的协议ID
func GetProtocolID(messageName string) (uint32, bool) {
	id, ok := AllMessageNameToID[messageName]
	return id, ok
}

// GetMessageName 获取指定协议ID的消息名称
func GetMessageName(pid uint32) (string, bool) {
	name, ok := AllIDToMessageName[pid]
	return name, ok
}

// GetResponsePID 获取响应消息的协议ID
func GetResponsePID(response proto.Message) uint32 {
	if response == nil {
		return 0
	}

	messageName := proto_utils.ParseMessageName(response)
	if messageName == "" {
		return 0
	}

	pid, ok := GetProtocolID(messageName)
	if !ok {
		panic(fmt.Sprintf("消息 %!s(MISSING) 未找到协议ID", messageName))
	}
	return pid
}
