// Code generated by genproto. DO NOT EDIT.
package pb

import (
	"fmt"

	"github.com/gogo/protobuf/proto"
)

// UnmarshalRequest 根据协议ID分发请求到对应处理函数
func UnmarshalRequest(pid uint32, data []byte) (proto.Message, error) {
	var req proto.Message
	switch pid {
	case PID_Request_SearchBook: // Request_SearchBook
		req = &Request_SearchBook{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("unmarshal Request_SearchBook failed: %w", err)
		}
	case PID_Request_HeartBeat: // Request_HeartBeat
		req = &Request_HeartBeat{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("unmarshal Request_HeartBeat failed: %w", err)
		}
	default:
		return nil, fmt.Errorf("unknown request protocol ID: 0x%08x", pid)
	}
	return req, nil
}

