// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0}
}

// 只有直接放在消息前的注释会被胶水代码读取
// 名字可以随便取，同一个包内不能重名
type Request_SearchBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"` //这行注释会被胶水代码读取
	PageNumber    int32                  `protobuf:"varint,2,opt,name=PageNumber,proto3" json:"PageNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchBook) Reset() {
	*x = Request_SearchBook{}
	mi := &file_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchBook) ProtoMessage() {}

func (x *Request_SearchBook) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchBook.ProtoReflect.Descriptor instead.
func (*Request_SearchBook) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_SearchBook) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Request_SearchBook) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

// 心跳
type Request_HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_HeartBeat) Reset() {
	*x = Request_HeartBeat{}
	mi := &file_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_HeartBeat) ProtoMessage() {}

func (x *Request_HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_HeartBeat.ProtoReflect.Descriptor instead.
func (*Request_HeartBeat) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0, 1}
}

// 该请求的回复消息，名字必须为Rsp，
// 如果没有，则默认回复为通用成功OK
type Request_SearchBook_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Book                  `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchBook_Rsp) Reset() {
	*x = Request_SearchBook_Rsp{}
	mi := &file_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchBook_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchBook_Rsp) ProtoMessage() {}

func (x *Request_SearchBook_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchBook_Rsp.ProtoReflect.Descriptor instead.
func (*Request_SearchBook_Rsp) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_SearchBook_Rsp) GetResult() *Book {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_request_proto protoreflect.FileDescriptor

const file_request_proto_rawDesc = "" +
	"\n" +
	"\rrequest.proto\x12\x02pb\x1a\rstructs.proto\x1a\fcommon.proto\"\x83\x01\n" +
	"\aRequest\x1ak\n" +
	"\n" +
	"SearchBook\x12\x14\n" +
	"\x05Query\x18\x01 \x01(\tR\x05Query\x12\x1e\n" +
	"\n" +
	"PageNumber\x18\x02 \x01(\x05R\n" +
	"PageNumber\x1a'\n" +
	"\x03Rsp\x12 \n" +
	"\x06Result\x18\x01 \x01(\v2\b.pb.BookR\x06Result\x1a\v\n" +
	"\tHeartBeatB&Z$gitee.com/orbit-w/orbit/app/proto/pbb\x06proto3"

var (
	file_request_proto_rawDescOnce sync.Once
	file_request_proto_rawDescData []byte
)

func file_request_proto_rawDescGZIP() []byte {
	file_request_proto_rawDescOnce.Do(func() {
		file_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)))
	})
	return file_request_proto_rawDescData
}

var file_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_request_proto_goTypes = []any{
	(*Request)(nil),                // 0: pb.Request
	(*Request_SearchBook)(nil),     // 1: pb.Request.SearchBook
	(*Request_HeartBeat)(nil),      // 2: pb.Request.HeartBeat
	(*Request_SearchBook_Rsp)(nil), // 3: pb.Request.SearchBook.Rsp
	(*Book)(nil),                   // 4: pb.Book
}
var file_request_proto_depIdxs = []int32{
	4, // 0: pb.Request.SearchBook.Rsp.Result:type_name -> pb.Book
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_proto_init() }
func file_request_proto_init() {
	if File_request_proto != nil {
		return
	}
	file_structs_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_goTypes,
		DependencyIndexes: file_request_proto_depIdxs,
		MessageInfos:      file_request_proto_msgTypes,
	}.Build()
	File_request_proto = out.File
	file_request_proto_goTypes = nil
	file_request_proto_depIdxs = nil
}
