// Code generated by genproto. DO NOT EDIT.
package pb

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
)

// RequestHandler 处理包的请求消息
type RequestHandler interface {
}

// DispatchRequestByID 根据协议ID分发请求到对应处理函数
func DispatchRequestByID(handler RequestHandler, pid uint32, data []byte) (proto.Message, uint32, error) {
	var response proto.Message
	switch pid {
	default:
		return nil, 0, fmt.Errorf("unknown request protocol ID: 0x%08x", pid)
	}

	// 使用公共映射文件获取响应ID
	responsePid := GetResponsePID(response)
	return response, responsePid, nil
}
