// Code generated by protocol ID generator. DO NOT EDIT.
package pb

// Protocol IDs for Season package messages
const (
	PID_Season_Request_SeasonInfo uint32 = 0xd9714656 // Season.Request_SeasonInfo
)

// MessageNameToID maps message names to their protocol IDs
var SeasonMessageNameToID = map[string]uint32{
	"Request_SeasonInfo": PID_Season_Request_SeasonInfo,
}

// IDToMessageName maps protocol IDs to their message names
var SeasonIDToMessageName = map[uint32]string{
	PID_Season_Request_SeasonInfo: "Request_SeasonInfo",
}

// GetProtocolID returns the protocol ID for the given message name
func GetSeasonProtocolID(messageName string) (uint32, bool) {
	id, ok := SeasonMessageNameToID[messageName]
	return id, ok
}

// GetMessageName returns the message name for the given protocol ID
func GetSeasonMessageName(pid uint32) (string, bool) {
	name, ok := SeasonIDToMessageName[pid]
	return name, ok
}
