// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: structs.proto

package pb

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPC请求消息定义
// 用于客户端向服务端发送RPC调用请求
type RpcHelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发送者进程ID，用于服务端回复消息
	Sender        *actor.PID `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcHelloRequest) Reset() {
	*x = RpcHelloRequest{}
	mi := &file_structs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHelloRequest) ProtoMessage() {}

func (x *RpcHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHelloRequest.ProtoReflect.Descriptor instead.
func (*RpcHelloRequest) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHelloRequest) GetSender() *actor.PID {
	if x != nil {
		return x.Sender
	}
	return nil
}

// RPC响应消息定义
// 用于服务端向客户端返回RPC调用结果
type RpcHelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应消息内容
	Message       string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcHelloResponse) Reset() {
	*x = RpcHelloResponse{}
	mi := &file_structs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHelloResponse) ProtoMessage() {}

func (x *RpcHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHelloResponse.ProtoReflect.Descriptor instead.
func (*RpcHelloResponse) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{1}
}

func (x *RpcHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --------在墙外定义的是单纯的数据结构，无法单独发送
type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"` //这行注释会被胶水代码读取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_structs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_structs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_structs_proto_rawDescGZIP(), []int{2}
}

func (x *Book) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_structs_proto protoreflect.FileDescriptor

const file_structs_proto_rawDesc = "" +
	"\n" +
	"\rstructs.proto\x12\x02pb\x1a\vactor.proto\"5\n" +
	"\x0fRpcHelloRequest\x12\"\n" +
	"\x06Sender\x18\x01 \x01(\v2\n" +
	".actor.PIDR\x06Sender\",\n" +
	"\x10RpcHelloResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\" \n" +
	"\x04Book\x12\x18\n" +
	"\aContent\x18\x01 \x01(\tR\aContentB&Z$gitee.com/orbit-w/orbit/app/proto/pbb\x06proto3"

var (
	file_structs_proto_rawDescOnce sync.Once
	file_structs_proto_rawDescData []byte
)

func file_structs_proto_rawDescGZIP() []byte {
	file_structs_proto_rawDescOnce.Do(func() {
		file_structs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_structs_proto_rawDesc), len(file_structs_proto_rawDesc)))
	})
	return file_structs_proto_rawDescData
}

var file_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_structs_proto_goTypes = []any{
	(*RpcHelloRequest)(nil),  // 0: pb.RpcHelloRequest
	(*RpcHelloResponse)(nil), // 1: pb.RpcHelloResponse
	(*Book)(nil),             // 2: pb.Book
	(*actor.PID)(nil),        // 3: actor.PID
}
var file_structs_proto_depIdxs = []int32{
	3, // 0: pb.RpcHelloRequest.Sender:type_name -> actor.PID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_structs_proto_init() }
func file_structs_proto_init() {
	if File_structs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_structs_proto_rawDesc), len(file_structs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_structs_proto_goTypes,
		DependencyIndexes: file_structs_proto_depIdxs,
		MessageInfos:      file_structs_proto_msgTypes,
	}.Build()
	File_structs_proto = out.File
	file_structs_proto_goTypes = nil
	file_structs_proto_depIdxs = nil
}
