// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: protocol/common.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_NONE   ChangeType = 0
	ChangeType_CHANGE_TYPE_SET    ChangeType = 1
	ChangeType_CHANGE_TYPE_DELETE ChangeType = 2
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_NONE",
		1: "CHANGE_TYPE_SET",
		2: "CHANGE_TYPE_DELETE",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_NONE":   0,
		"CHANGE_TYPE_SET":    1,
		"CHANGE_TYPE_DELETE": 2,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_protocol_common_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{0}
}

var File_protocol_common_proto protoreflect.FileDescriptor

const file_protocol_common_proto_rawDesc = "" +
	"\n" +
	"\x15protocol/common.proto\x12\x03MME*O\n" +
	"\n" +
	"ChangeType\x12\x14\n" +
	"\x10CHANGE_TYPE_NONE\x10\x00\x12\x13\n" +
	"\x0fCHANGE_TYPE_SET\x10\x01\x12\x16\n" +
	"\x12CHANGE_TYPE_DELETE\x10\x02B\aZ\x05./mmeb\x06proto3"

var (
	file_protocol_common_proto_rawDescOnce sync.Once
	file_protocol_common_proto_rawDescData []byte
)

func file_protocol_common_proto_rawDescGZIP() []byte {
	file_protocol_common_proto_rawDescOnce.Do(func() {
		file_protocol_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_common_proto_rawDesc), len(file_protocol_common_proto_rawDesc)))
	})
	return file_protocol_common_proto_rawDescData
}

var file_protocol_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_common_proto_goTypes = []any{
	(ChangeType)(0), // 0: MME.ChangeType
}
var file_protocol_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_common_proto_init() }
func file_protocol_common_proto_init() {
	if File_protocol_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_common_proto_rawDesc), len(file_protocol_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_proto_goTypes,
		DependencyIndexes: file_protocol_common_proto_depIdxs,
		EnumInfos:         file_protocol_common_proto_enumTypes,
	}.Build()
	File_protocol_common_proto = out.File
	file_protocol_common_proto_goTypes = nil
	file_protocol_common_proto_depIdxs = nil
}
