// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protocol/managers.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeroManager struct {
	state                 protoimpl.MessageState                    `protogen:"open.v1"`
	HeroMap               map[int64]*HeroModule                     `protobuf:"bytes,1,rep,name=HeroMap,proto3" json:"HeroMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HeroMap_XXXChangeList []*HeroManager_HeroMap_XXXMapChangeRecord `protobuf:"bytes,1001,rep,name=HeroMap_XXXChangeList,json=HeroMapXXXChangeList,proto3" json:"HeroMap_XXXChangeList,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeroManager) Reset() {
	*x = HeroManager{}
	mi := &file_protocol_managers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroManager) ProtoMessage() {}

func (x *HeroManager) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_managers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroManager.ProtoReflect.Descriptor instead.
func (*HeroManager) Descriptor() ([]byte, []int) {
	return file_protocol_managers_proto_rawDescGZIP(), []int{0}
}

func (x *HeroManager) GetHeroMap() map[int64]*HeroModule {
	if x != nil {
		return x.HeroMap
	}
	return nil
}

func (x *HeroManager) GetHeroMap_XXXChangeList() []*HeroManager_HeroMap_XXXMapChangeRecord {
	if x != nil {
		return x.HeroMap_XXXChangeList
	}
	return nil
}

type HeroManager_HeroMap_XXXMapChangeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *HeroModule            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsDelete      bool                   `protobuf:"varint,3,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroManager_HeroMap_XXXMapChangeRecord) Reset() {
	*x = HeroManager_HeroMap_XXXMapChangeRecord{}
	mi := &file_protocol_managers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroManager_HeroMap_XXXMapChangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroManager_HeroMap_XXXMapChangeRecord) ProtoMessage() {}

func (x *HeroManager_HeroMap_XXXMapChangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_managers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroManager_HeroMap_XXXMapChangeRecord.ProtoReflect.Descriptor instead.
func (*HeroManager_HeroMap_XXXMapChangeRecord) Descriptor() ([]byte, []int) {
	return file_protocol_managers_proto_rawDescGZIP(), []int{0, 1}
}

func (x *HeroManager_HeroMap_XXXMapChangeRecord) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *HeroManager_HeroMap_XXXMapChangeRecord) GetValue() *HeroModule {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HeroManager_HeroMap_XXXMapChangeRecord) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

var File_protocol_managers_proto protoreflect.FileDescriptor

const file_protocol_managers_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/managers.proto\x12\bmanagers\x1a\x16protocol/modules.proto\"\xfb\x02\n" +
	"\vHeroManager\x12<\n" +
	"\aHeroMap\x18\x01 \x03(\v2\".managers.HeroManager.HeroMapEntryR\aHeroMap\x12f\n" +
	"\x15HeroMap_XXXChangeList\x18\xe9\a \x03(\v20.managers.HeroManager.HeroMap_XXXMapChangeRecordR\x14HeroMapXXXChangeList\x1aO\n" +
	"\fHeroMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.modules.HeroModuleR\x05value:\x028\x01\x1au\n" +
	"\x1aHeroMap_XXXMapChangeRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.modules.HeroModuleR\x05value\x12\x1a\n" +
	"\bisDelete\x18\x03 \x01(\bR\bisDeleteB\aZ\x05./mmeb\x06proto3"

var (
	file_protocol_managers_proto_rawDescOnce sync.Once
	file_protocol_managers_proto_rawDescData []byte
)

func file_protocol_managers_proto_rawDescGZIP() []byte {
	file_protocol_managers_proto_rawDescOnce.Do(func() {
		file_protocol_managers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_managers_proto_rawDesc), len(file_protocol_managers_proto_rawDesc)))
	})
	return file_protocol_managers_proto_rawDescData
}

var file_protocol_managers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_managers_proto_goTypes = []any{
	(*HeroManager)(nil), // 0: managers.HeroManager
	nil,                 // 1: managers.HeroManager.HeroMapEntry
	(*HeroManager_HeroMap_XXXMapChangeRecord)(nil), // 2: managers.HeroManager.HeroMap_XXXMapChangeRecord
	(*HeroModule)(nil), // 3: modules.HeroModule
}
var file_protocol_managers_proto_depIdxs = []int32{
	1, // 0: managers.HeroManager.HeroMap:type_name -> managers.HeroManager.HeroMapEntry
	2, // 1: managers.HeroManager.HeroMap_XXXChangeList:type_name -> managers.HeroManager.HeroMap_XXXMapChangeRecord
	3, // 2: managers.HeroManager.HeroMapEntry.value:type_name -> modules.HeroModule
	3, // 3: managers.HeroManager.HeroMap_XXXMapChangeRecord.value:type_name -> modules.HeroModule
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protocol_managers_proto_init() }
func file_protocol_managers_proto_init() {
	if File_protocol_managers_proto != nil {
		return
	}
	file_protocol_modules_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_managers_proto_rawDesc), len(file_protocol_managers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_managers_proto_goTypes,
		DependencyIndexes: file_protocol_managers_proto_depIdxs,
		MessageInfos:      file_protocol_managers_proto_msgTypes,
	}.Build()
	File_protocol_managers_proto = out.File
	file_protocol_managers_proto_goTypes = nil
	file_protocol_managers_proto_depIdxs = nil
}
