// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protocol/mechanisms.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 升级机制
type LevelUpMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurLevel      *int32                 `protobuf:"varint,1,opt,name=CurLevel,proto3,oneof" json:"CurLevel,omitempty"` // 当前等级
	CurExp        *int32                 `protobuf:"varint,2,opt,name=CurExp,proto3,oneof" json:"CurExp,omitempty"`     // 当前经验值
	ConfId        *int32                 `protobuf:"varint,3,opt,name=ConfId,proto3,oneof" json:"ConfId,omitempty"`     // 走哪套升级配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUpMechanism) Reset() {
	*x = LevelUpMechanism{}
	mi := &file_protocol_mechanisms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpMechanism) ProtoMessage() {}

func (x *LevelUpMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_mechanisms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpMechanism.ProtoReflect.Descriptor instead.
func (*LevelUpMechanism) Descriptor() ([]byte, []int) {
	return file_protocol_mechanisms_proto_rawDescGZIP(), []int{0}
}

func (x *LevelUpMechanism) GetCurLevel() int32 {
	if x != nil && x.CurLevel != nil {
		return *x.CurLevel
	}
	return 0
}

func (x *LevelUpMechanism) GetCurExp() int32 {
	if x != nil && x.CurExp != nil {
		return *x.CurExp
	}
	return 0
}

func (x *LevelUpMechanism) GetConfId() int32 {
	if x != nil && x.ConfId != nil {
		return *x.ConfId
	}
	return 0
}

// 升级机制设置
type LevelUpMechanismSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AutoLevelUp   *bool                  `protobuf:"varint,1,opt,name=AutoLevelUp,proto3,oneof" json:"AutoLevelUp,omitempty"` // 经验够则自动升级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUpMechanismSettings) Reset() {
	*x = LevelUpMechanismSettings{}
	mi := &file_protocol_mechanisms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpMechanismSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpMechanismSettings) ProtoMessage() {}

func (x *LevelUpMechanismSettings) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_mechanisms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpMechanismSettings.ProtoReflect.Descriptor instead.
func (*LevelUpMechanismSettings) Descriptor() ([]byte, []int) {
	return file_protocol_mechanisms_proto_rawDescGZIP(), []int{1}
}

func (x *LevelUpMechanismSettings) GetAutoLevelUp() bool {
	if x != nil && x.AutoLevelUp != nil {
		return *x.AutoLevelUp
	}
	return false
}

// 英雄机制
type HeroMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=Id,proto3,oneof" json:"Id,omitempty"`                                                                              // 英雄实例唯一Id
	ConfId        *int32                 `protobuf:"varint,2,opt,name=ConfId,proto3,oneof" json:"ConfId,omitempty"`                                                                      // 英雄配置ID
	CreateTime    *int64                 `protobuf:"varint,3,opt,name=CreateTime,proto3,oneof" json:"CreateTime,omitempty"`                                                              // 玩家获得英雄的时间
	UseTimes      *int32                 `protobuf:"varint,4,opt,name=UseTimes,proto3,oneof" json:"UseTimes,omitempty"`                                                                  // 英雄被使用次数
	Skills        map[int32]int32        `protobuf:"bytes,5,rep,name=Skills,proto3" json:"Skills,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 技能
	SkillChanges  []*SkillXXXChange      `protobuf:"bytes,1005,rep,name=SkillChanges,proto3" json:"SkillChanges,omitempty"`                                                              // 技能变化
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroMechanism) Reset() {
	*x = HeroMechanism{}
	mi := &file_protocol_mechanisms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroMechanism) ProtoMessage() {}

func (x *HeroMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_mechanisms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroMechanism.ProtoReflect.Descriptor instead.
func (*HeroMechanism) Descriptor() ([]byte, []int) {
	return file_protocol_mechanisms_proto_rawDescGZIP(), []int{2}
}

func (x *HeroMechanism) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *HeroMechanism) GetConfId() int32 {
	if x != nil && x.ConfId != nil {
		return *x.ConfId
	}
	return 0
}

func (x *HeroMechanism) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *HeroMechanism) GetUseTimes() int32 {
	if x != nil && x.UseTimes != nil {
		return *x.UseTimes
	}
	return 0
}

func (x *HeroMechanism) GetSkills() map[int32]int32 {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *HeroMechanism) GetSkillChanges() []*SkillXXXChange {
	if x != nil {
		return x.SkillChanges
	}
	return nil
}

// XXXChange 是根据HeroMechanism结构体中Skills字段自动化生成的，用于记录技能变化。结构模式固定，不要修改。
type SkillXXXChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangeType             `protobuf:"varint,1,opt,name=ChangeType,proto3,enum=common.ChangeType" json:"ChangeType,omitempty"`
	Key           int32                  `protobuf:"varint,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         *int32                 `protobuf:"varint,3,opt,name=Value,proto3,oneof" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillXXXChange) Reset() {
	*x = SkillXXXChange{}
	mi := &file_protocol_mechanisms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillXXXChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillXXXChange) ProtoMessage() {}

func (x *SkillXXXChange) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_mechanisms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillXXXChange.ProtoReflect.Descriptor instead.
func (*SkillXXXChange) Descriptor() ([]byte, []int) {
	return file_protocol_mechanisms_proto_rawDescGZIP(), []int{3}
}

func (x *SkillXXXChange) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_NONE
}

func (x *SkillXXXChange) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *SkillXXXChange) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// 手动解锁机制
type ManualUnlockMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnlockMap     map[int32]bool         `protobuf:"bytes,1,rep,name=UnlockMap,proto3" json:"UnlockMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 解锁状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualUnlockMechanism) Reset() {
	*x = ManualUnlockMechanism{}
	mi := &file_protocol_mechanisms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualUnlockMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualUnlockMechanism) ProtoMessage() {}

func (x *ManualUnlockMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_mechanisms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualUnlockMechanism.ProtoReflect.Descriptor instead.
func (*ManualUnlockMechanism) Descriptor() ([]byte, []int) {
	return file_protocol_mechanisms_proto_rawDescGZIP(), []int{4}
}

func (x *ManualUnlockMechanism) GetUnlockMap() map[int32]bool {
	if x != nil {
		return x.UnlockMap
	}
	return nil
}

// 穿戴机制
type WearMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WearMap       map[int32]int32        `protobuf:"bytes,1,rep,name=WearMap,proto3" json:"WearMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 穿戴状态
	ConfId        *int32                 `protobuf:"varint,2,opt,name=ConfId,proto3,oneof" json:"ConfId,omitempty"`                                                                        // 走哪套穿戴配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WearMechanism) Reset() {
	*x = WearMechanism{}
	mi := &file_protocol_mechanisms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WearMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WearMechanism) ProtoMessage() {}

func (x *WearMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_mechanisms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WearMechanism.ProtoReflect.Descriptor instead.
func (*WearMechanism) Descriptor() ([]byte, []int) {
	return file_protocol_mechanisms_proto_rawDescGZIP(), []int{5}
}

func (x *WearMechanism) GetWearMap() map[int32]int32 {
	if x != nil {
		return x.WearMap
	}
	return nil
}

func (x *WearMechanism) GetConfId() int32 {
	if x != nil && x.ConfId != nil {
		return *x.ConfId
	}
	return 0
}

var File_protocol_mechanisms_proto protoreflect.FileDescriptor

const file_protocol_mechanisms_proto_rawDesc = "" +
	"\n" +
	"\x19protocol/mechanisms.proto\x12\n" +
	"mechanisms\x1a\x15protocol/common.proto\"\x90\x01\n" +
	"\x10LevelUpMechanism\x12\x1f\n" +
	"\bCurLevel\x18\x01 \x01(\x05H\x00R\bCurLevel\x88\x01\x01\x12\x1b\n" +
	"\x06CurExp\x18\x02 \x01(\x05H\x01R\x06CurExp\x88\x01\x01\x12\x1b\n" +
	"\x06ConfId\x18\x03 \x01(\x05H\x02R\x06ConfId\x88\x01\x01B\v\n" +
	"\t_CurLevelB\t\n" +
	"\a_CurExpB\t\n" +
	"\a_ConfId\"Q\n" +
	"\x18LevelUpMechanismSettings\x12%\n" +
	"\vAutoLevelUp\x18\x01 \x01(\bH\x00R\vAutoLevelUp\x88\x01\x01B\x0e\n" +
	"\f_AutoLevelUp\"\xf0\x02\n" +
	"\rHeroMechanism\x12\x13\n" +
	"\x02Id\x18\x01 \x01(\x03H\x00R\x02Id\x88\x01\x01\x12\x1b\n" +
	"\x06ConfId\x18\x02 \x01(\x05H\x01R\x06ConfId\x88\x01\x01\x12#\n" +
	"\n" +
	"CreateTime\x18\x03 \x01(\x03H\x02R\n" +
	"CreateTime\x88\x01\x01\x12\x1f\n" +
	"\bUseTimes\x18\x04 \x01(\x05H\x03R\bUseTimes\x88\x01\x01\x12=\n" +
	"\x06Skills\x18\x05 \x03(\v2%.mechanisms.HeroMechanism.SkillsEntryR\x06Skills\x12?\n" +
	"\fSkillChanges\x18\xed\a \x03(\v2\x1a.mechanisms.SkillXXXChangeR\fSkillChanges\x1a9\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x05\n" +
	"\x03_IdB\t\n" +
	"\a_ConfIdB\r\n" +
	"\v_CreateTimeB\v\n" +
	"\t_UseTimes\"{\n" +
	"\x0eSkillXXXChange\x122\n" +
	"\n" +
	"ChangeType\x18\x01 \x01(\x0e2\x12.common.ChangeTypeR\n" +
	"ChangeType\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\x05R\x03Key\x12\x19\n" +
	"\x05Value\x18\x03 \x01(\x05H\x00R\x05Value\x88\x01\x01B\b\n" +
	"\x06_Value\"\xa5\x01\n" +
	"\x15ManualUnlockMechanism\x12N\n" +
	"\tUnlockMap\x18\x01 \x03(\v20.mechanisms.ManualUnlockMechanism.UnlockMapEntryR\tUnlockMap\x1a<\n" +
	"\x0eUnlockMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xb5\x01\n" +
	"\rWearMechanism\x12@\n" +
	"\aWearMap\x18\x01 \x03(\v2&.mechanisms.WearMechanism.WearMapEntryR\aWearMap\x12\x1b\n" +
	"\x06ConfId\x18\x02 \x01(\x05H\x00R\x06ConfId\x88\x01\x01\x1a:\n" +
	"\fWearMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\t\n" +
	"\a_ConfIdB\aZ\x05./mmeb\x06proto3"

var (
	file_protocol_mechanisms_proto_rawDescOnce sync.Once
	file_protocol_mechanisms_proto_rawDescData []byte
)

func file_protocol_mechanisms_proto_rawDescGZIP() []byte {
	file_protocol_mechanisms_proto_rawDescOnce.Do(func() {
		file_protocol_mechanisms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_mechanisms_proto_rawDesc), len(file_protocol_mechanisms_proto_rawDesc)))
	})
	return file_protocol_mechanisms_proto_rawDescData
}

var file_protocol_mechanisms_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protocol_mechanisms_proto_goTypes = []any{
	(*LevelUpMechanism)(nil),         // 0: mechanisms.LevelUpMechanism
	(*LevelUpMechanismSettings)(nil), // 1: mechanisms.LevelUpMechanismSettings
	(*HeroMechanism)(nil),            // 2: mechanisms.HeroMechanism
	(*SkillXXXChange)(nil),           // 3: mechanisms.SkillXXXChange
	(*ManualUnlockMechanism)(nil),    // 4: mechanisms.ManualUnlockMechanism
	(*WearMechanism)(nil),            // 5: mechanisms.WearMechanism
	nil,                              // 6: mechanisms.HeroMechanism.SkillsEntry
	nil,                              // 7: mechanisms.ManualUnlockMechanism.UnlockMapEntry
	nil,                              // 8: mechanisms.WearMechanism.WearMapEntry
	(ChangeType)(0),                  // 9: common.ChangeType
}
var file_protocol_mechanisms_proto_depIdxs = []int32{
	6, // 0: mechanisms.HeroMechanism.Skills:type_name -> mechanisms.HeroMechanism.SkillsEntry
	3, // 1: mechanisms.HeroMechanism.SkillChanges:type_name -> mechanisms.SkillXXXChange
	9, // 2: mechanisms.SkillXXXChange.ChangeType:type_name -> common.ChangeType
	7, // 3: mechanisms.ManualUnlockMechanism.UnlockMap:type_name -> mechanisms.ManualUnlockMechanism.UnlockMapEntry
	8, // 4: mechanisms.WearMechanism.WearMap:type_name -> mechanisms.WearMechanism.WearMapEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protocol_mechanisms_proto_init() }
func file_protocol_mechanisms_proto_init() {
	if File_protocol_mechanisms_proto != nil {
		return
	}
	file_protocol_common_proto_init()
	file_protocol_mechanisms_proto_msgTypes[0].OneofWrappers = []any{}
	file_protocol_mechanisms_proto_msgTypes[1].OneofWrappers = []any{}
	file_protocol_mechanisms_proto_msgTypes[2].OneofWrappers = []any{}
	file_protocol_mechanisms_proto_msgTypes[3].OneofWrappers = []any{}
	file_protocol_mechanisms_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_mechanisms_proto_rawDesc), len(file_protocol_mechanisms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_mechanisms_proto_goTypes,
		DependencyIndexes: file_protocol_mechanisms_proto_depIdxs,
		MessageInfos:      file_protocol_mechanisms_proto_msgTypes,
	}.Build()
	File_protocol_mechanisms_proto = out.File
	file_protocol_mechanisms_proto_goTypes = nil
	file_protocol_mechanisms_proto_depIdxs = nil
}
