// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mechanisms.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LevelUpMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurLevel      *int32                 `protobuf:"varint,1,opt,name=CurLevel,proto3,oneof" json:"CurLevel,omitempty"`
	CurExp        *int32                 `protobuf:"varint,2,opt,name=CurExp,proto3,oneof" json:"CurExp,omitempty"`
	ConfId        *int32                 `protobuf:"varint,3,opt,name=ConfId,proto3,oneof" json:"ConfId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUpMechanism) Reset() {
	*x = LevelUpMechanism{}
	mi := &file_mechanisms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpMechanism) ProtoMessage() {}

func (x *LevelUpMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_mechanisms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpMechanism.ProtoReflect.Descriptor instead.
func (*LevelUpMechanism) Descriptor() ([]byte, []int) {
	return file_mechanisms_proto_rawDescGZIP(), []int{0}
}

func (x *LevelUpMechanism) GetCurLevel() int32 {
	if x != nil && x.CurLevel != nil {
		return *x.CurLevel
	}
	return 0
}

func (x *LevelUpMechanism) GetCurExp() int32 {
	if x != nil && x.CurExp != nil {
		return *x.CurExp
	}
	return 0
}

func (x *LevelUpMechanism) GetConfId() int32 {
	if x != nil && x.ConfId != nil {
		return *x.ConfId
	}
	return 0
}

type HeroMechanism struct {
	state                protoimpl.MessageState                     `protogen:"open.v1"`
	Id                   *int64                                     `protobuf:"varint,1,opt,name=Id,proto3,oneof" json:"Id,omitempty"`
	ConfId               *int32                                     `protobuf:"varint,2,opt,name=ConfId,proto3,oneof" json:"ConfId,omitempty"`
	CreateTime           *int64                                     `protobuf:"varint,3,opt,name=CreateTime,proto3,oneof" json:"CreateTime,omitempty"`
	UseTimes             *int32                                     `protobuf:"varint,4,opt,name=UseTimes,proto3,oneof" json:"UseTimes,omitempty"`
	Skills               map[int32]int32                            `protobuf:"bytes,5,rep,name=Skills,proto3" json:"Skills,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Skills_XXXChangeList []*HeroMechanism_Skills_XXXMapChangeRecord `protobuf:"bytes,1005,rep,name=Skills_XXXChangeList,json=SkillsXXXChangeList,proto3" json:"Skills_XXXChangeList,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeroMechanism) Reset() {
	*x = HeroMechanism{}
	mi := &file_mechanisms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroMechanism) ProtoMessage() {}

func (x *HeroMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_mechanisms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroMechanism.ProtoReflect.Descriptor instead.
func (*HeroMechanism) Descriptor() ([]byte, []int) {
	return file_mechanisms_proto_rawDescGZIP(), []int{1}
}

func (x *HeroMechanism) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *HeroMechanism) GetConfId() int32 {
	if x != nil && x.ConfId != nil {
		return *x.ConfId
	}
	return 0
}

func (x *HeroMechanism) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *HeroMechanism) GetUseTimes() int32 {
	if x != nil && x.UseTimes != nil {
		return *x.UseTimes
	}
	return 0
}

func (x *HeroMechanism) GetSkills() map[int32]int32 {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *HeroMechanism) GetSkills_XXXChangeList() []*HeroMechanism_Skills_XXXMapChangeRecord {
	if x != nil {
		return x.Skills_XXXChangeList
	}
	return nil
}

type ManualUnlockMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnlockMap     map[int32]bool         `protobuf:"bytes,1,rep,name=UnlockMap,proto3" json:"UnlockMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualUnlockMechanism) Reset() {
	*x = ManualUnlockMechanism{}
	mi := &file_mechanisms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualUnlockMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualUnlockMechanism) ProtoMessage() {}

func (x *ManualUnlockMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_mechanisms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualUnlockMechanism.ProtoReflect.Descriptor instead.
func (*ManualUnlockMechanism) Descriptor() ([]byte, []int) {
	return file_mechanisms_proto_rawDescGZIP(), []int{2}
}

func (x *ManualUnlockMechanism) GetUnlockMap() map[int32]bool {
	if x != nil {
		return x.UnlockMap
	}
	return nil
}

type WearMechanism struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WearMap       map[int32]int32        `protobuf:"bytes,1,rep,name=WearMap,proto3" json:"WearMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ConfId        *int32                 `protobuf:"varint,2,opt,name=ConfId,proto3,oneof" json:"ConfId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WearMechanism) Reset() {
	*x = WearMechanism{}
	mi := &file_mechanisms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WearMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WearMechanism) ProtoMessage() {}

func (x *WearMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_mechanisms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WearMechanism.ProtoReflect.Descriptor instead.
func (*WearMechanism) Descriptor() ([]byte, []int) {
	return file_mechanisms_proto_rawDescGZIP(), []int{3}
}

func (x *WearMechanism) GetWearMap() map[int32]int32 {
	if x != nil {
		return x.WearMap
	}
	return nil
}

func (x *WearMechanism) GetConfId() int32 {
	if x != nil && x.ConfId != nil {
		return *x.ConfId
	}
	return 0
}

type HeroMechanism_Skills_XXXMapChangeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	IsDelete      bool                   `protobuf:"varint,3,opt,name=IsDelete,proto3" json:"IsDelete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroMechanism_Skills_XXXMapChangeRecord) Reset() {
	*x = HeroMechanism_Skills_XXXMapChangeRecord{}
	mi := &file_mechanisms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroMechanism_Skills_XXXMapChangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroMechanism_Skills_XXXMapChangeRecord) ProtoMessage() {}

func (x *HeroMechanism_Skills_XXXMapChangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mechanisms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroMechanism_Skills_XXXMapChangeRecord.ProtoReflect.Descriptor instead.
func (*HeroMechanism_Skills_XXXMapChangeRecord) Descriptor() ([]byte, []int) {
	return file_mechanisms_proto_rawDescGZIP(), []int{1, 1}
}

func (x *HeroMechanism_Skills_XXXMapChangeRecord) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *HeroMechanism_Skills_XXXMapChangeRecord) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *HeroMechanism_Skills_XXXMapChangeRecord) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

var File_mechanisms_proto protoreflect.FileDescriptor

const file_mechanisms_proto_rawDesc = "" +
	"\n" +
	"\x10mechanisms.proto\x12\x03MME\x1a\fcommon.proto\"\x90\x01\n" +
	"\x10LevelUpMechanism\x12\x1f\n" +
	"\bCurLevel\x18\x01 \x01(\x05H\x00R\bCurLevel\x88\x01\x01\x12\x1b\n" +
	"\x06CurExp\x18\x02 \x01(\x05H\x01R\x06CurExp\x88\x01\x01\x12\x1b\n" +
	"\x06ConfId\x18\x03 \x01(\x05H\x02R\x06ConfId\x88\x01\x01B\v\n" +
	"\t_CurLevelB\t\n" +
	"\a_CurExpB\t\n" +
	"\a_ConfId\"\xeb\x03\n" +
	"\rHeroMechanism\x12\x13\n" +
	"\x02Id\x18\x01 \x01(\x03H\x00R\x02Id\x88\x01\x01\x12\x1b\n" +
	"\x06ConfId\x18\x02 \x01(\x05H\x01R\x06ConfId\x88\x01\x01\x12#\n" +
	"\n" +
	"CreateTime\x18\x03 \x01(\x03H\x02R\n" +
	"CreateTime\x88\x01\x01\x12\x1f\n" +
	"\bUseTimes\x18\x04 \x01(\x05H\x03R\bUseTimes\x88\x01\x01\x126\n" +
	"\x06Skills\x18\x05 \x03(\v2\x1e.MME.HeroMechanism.SkillsEntryR\x06Skills\x12`\n" +
	"\x14Skills_XXXChangeList\x18\xed\a \x03(\v2,.MME.HeroMechanism.Skills_XXXMapChangeRecordR\x13SkillsXXXChangeList\x1a9\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a_\n" +
	"\x19Skills_XXXMapChangeRecord\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\x05R\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x05R\x05Value\x12\x1a\n" +
	"\bIsDelete\x18\x03 \x01(\bR\bIsDeleteB\x05\n" +
	"\x03_IdB\t\n" +
	"\a_ConfIdB\r\n" +
	"\v_CreateTimeB\v\n" +
	"\t_UseTimes\"\x9e\x01\n" +
	"\x15ManualUnlockMechanism\x12G\n" +
	"\tUnlockMap\x18\x01 \x03(\v2).MME.ManualUnlockMechanism.UnlockMapEntryR\tUnlockMap\x1a<\n" +
	"\x0eUnlockMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xae\x01\n" +
	"\rWearMechanism\x129\n" +
	"\aWearMap\x18\x01 \x03(\v2\x1f.MME.WearMechanism.WearMapEntryR\aWearMap\x12\x1b\n" +
	"\x06ConfId\x18\x02 \x01(\x05H\x00R\x06ConfId\x88\x01\x01\x1a:\n" +
	"\fWearMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\t\n" +
	"\a_ConfIdB'Z%gitee.com/orbit-w/orbit/app/proto/mmeb\x06proto3"

var (
	file_mechanisms_proto_rawDescOnce sync.Once
	file_mechanisms_proto_rawDescData []byte
)

func file_mechanisms_proto_rawDescGZIP() []byte {
	file_mechanisms_proto_rawDescOnce.Do(func() {
		file_mechanisms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mechanisms_proto_rawDesc), len(file_mechanisms_proto_rawDesc)))
	})
	return file_mechanisms_proto_rawDescData
}

var file_mechanisms_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mechanisms_proto_goTypes = []any{
	(*LevelUpMechanism)(nil),      // 0: MME.LevelUpMechanism
	(*HeroMechanism)(nil),         // 1: MME.HeroMechanism
	(*ManualUnlockMechanism)(nil), // 2: MME.ManualUnlockMechanism
	(*WearMechanism)(nil),         // 3: MME.WearMechanism
	nil,                           // 4: MME.HeroMechanism.SkillsEntry
	(*HeroMechanism_Skills_XXXMapChangeRecord)(nil), // 5: MME.HeroMechanism.Skills_XXXMapChangeRecord
	nil, // 6: MME.ManualUnlockMechanism.UnlockMapEntry
	nil, // 7: MME.WearMechanism.WearMapEntry
}
var file_mechanisms_proto_depIdxs = []int32{
	4, // 0: MME.HeroMechanism.Skills:type_name -> MME.HeroMechanism.SkillsEntry
	5, // 1: MME.HeroMechanism.Skills_XXXChangeList:type_name -> MME.HeroMechanism.Skills_XXXMapChangeRecord
	6, // 2: MME.ManualUnlockMechanism.UnlockMap:type_name -> MME.ManualUnlockMechanism.UnlockMapEntry
	7, // 3: MME.WearMechanism.WearMap:type_name -> MME.WearMechanism.WearMapEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mechanisms_proto_init() }
func file_mechanisms_proto_init() {
	if File_mechanisms_proto != nil {
		return
	}
	file_common_proto_init()
	file_mechanisms_proto_msgTypes[0].OneofWrappers = []any{}
	file_mechanisms_proto_msgTypes[1].OneofWrappers = []any{}
	file_mechanisms_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mechanisms_proto_rawDesc), len(file_mechanisms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mechanisms_proto_goTypes,
		DependencyIndexes: file_mechanisms_proto_depIdxs,
		MessageInfos:      file_mechanisms_proto_msgTypes,
	}.Build()
	File_mechanisms_proto = out.File
	file_mechanisms_proto_goTypes = nil
	file_mechanisms_proto_depIdxs = nil
}
