// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: protocol/modules.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeroModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *HeroMechanism         `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	LevelUp       *LevelUpMechanism      `protobuf:"bytes,2,opt,name=LevelUp,proto3" json:"LevelUp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroModule) Reset() {
	*x = HeroModule{}
	mi := &file_protocol_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroModule) ProtoMessage() {}

func (x *HeroModule) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroModule.ProtoReflect.Descriptor instead.
func (*HeroModule) Descriptor() ([]byte, []int) {
	return file_protocol_modules_proto_rawDescGZIP(), []int{0}
}

func (x *HeroModule) GetBase() *HeroMechanism {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *HeroModule) GetLevelUp() *LevelUpMechanism {
	if x != nil {
		return x.LevelUp
	}
	return nil
}

var File_protocol_modules_proto protoreflect.FileDescriptor

const file_protocol_modules_proto_rawDesc = "" +
	"\n" +
	"\x16protocol/modules.proto\x12\amodules\x1a\x19protocol/mechanisms.proto\"s\n" +
	"\n" +
	"HeroModule\x12-\n" +
	"\x04Base\x18\x01 \x01(\v2\x19.mechanisms.HeroMechanismR\x04Base\x126\n" +
	"\aLevelUp\x18\x02 \x01(\v2\x1c.mechanisms.LevelUpMechanismR\aLevelUpB\aZ\x05./mmeb\x06proto3"

var (
	file_protocol_modules_proto_rawDescOnce sync.Once
	file_protocol_modules_proto_rawDescData []byte
)

func file_protocol_modules_proto_rawDescGZIP() []byte {
	file_protocol_modules_proto_rawDescOnce.Do(func() {
		file_protocol_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_modules_proto_rawDesc), len(file_protocol_modules_proto_rawDesc)))
	})
	return file_protocol_modules_proto_rawDescData
}

var file_protocol_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_modules_proto_goTypes = []any{
	(*HeroModule)(nil),       // 0: modules.HeroModule
	(*HeroMechanism)(nil),    // 1: mechanisms.HeroMechanism
	(*LevelUpMechanism)(nil), // 2: mechanisms.LevelUpMechanism
}
var file_protocol_modules_proto_depIdxs = []int32{
	1, // 0: modules.HeroModule.Base:type_name -> mechanisms.HeroMechanism
	2, // 1: modules.HeroModule.LevelUp:type_name -> mechanisms.LevelUpMechanism
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_modules_proto_init() }
func file_protocol_modules_proto_init() {
	if File_protocol_modules_proto != nil {
		return
	}
	file_protocol_mechanisms_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_modules_proto_rawDesc), len(file_protocol_modules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_modules_proto_goTypes,
		DependencyIndexes: file_protocol_modules_proto_depIdxs,
		MessageInfos:      file_protocol_modules_proto_msgTypes,
	}.Build()
	File_protocol_modules_proto = out.File
	file_protocol_modules_proto_goTypes = nil
	file_protocol_modules_proto_depIdxs = nil
}
