// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: modules.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeroModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *HeroMechanism         `protobuf:"bytes,1,opt,name=Base,proto3,oneof" json:"Base,omitempty"`
	LevelUp       *LevelUpMechanism      `protobuf:"bytes,2,opt,name=LevelUp,proto3,oneof" json:"LevelUp,omitempty"`
	TalentUnlock  *ManualUnlockMechanism `protobuf:"bytes,3,opt,name=TalentUnlock,proto3,oneof" json:"TalentUnlock,omitempty"`
	SkinWear      *WearMechanism         `protobuf:"bytes,4,opt,name=SkinWear,proto3,oneof" json:"SkinWear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroModule) Reset() {
	*x = HeroModule{}
	mi := &file_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroModule) ProtoMessage() {}

func (x *HeroModule) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroModule.ProtoReflect.Descriptor instead.
func (*HeroModule) Descriptor() ([]byte, []int) {
	return file_modules_proto_rawDescGZIP(), []int{0}
}

func (x *HeroModule) GetBase() *HeroMechanism {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *HeroModule) GetLevelUp() *LevelUpMechanism {
	if x != nil {
		return x.LevelUp
	}
	return nil
}

func (x *HeroModule) GetTalentUnlock() *ManualUnlockMechanism {
	if x != nil {
		return x.TalentUnlock
	}
	return nil
}

func (x *HeroModule) GetSkinWear() *WearMechanism {
	if x != nil {
		return x.SkinWear
	}
	return nil
}

var File_modules_proto protoreflect.FileDescriptor

const file_modules_proto_rawDesc = "" +
	"\n" +
	"\rmodules.proto\x12\x03MME\x1a\x10mechanisms.proto\"\x9c\x02\n" +
	"\n" +
	"HeroModule\x12+\n" +
	"\x04Base\x18\x01 \x01(\v2\x12.MME.HeroMechanismH\x00R\x04Base\x88\x01\x01\x124\n" +
	"\aLevelUp\x18\x02 \x01(\v2\x15.MME.LevelUpMechanismH\x01R\aLevelUp\x88\x01\x01\x12C\n" +
	"\fTalentUnlock\x18\x03 \x01(\v2\x1a.MME.ManualUnlockMechanismH\x02R\fTalentUnlock\x88\x01\x01\x123\n" +
	"\bSkinWear\x18\x04 \x01(\v2\x12.MME.WearMechanismH\x03R\bSkinWear\x88\x01\x01B\a\n" +
	"\x05_BaseB\n" +
	"\n" +
	"\b_LevelUpB\x0f\n" +
	"\r_TalentUnlockB\v\n" +
	"\t_SkinWearB'Z%gitee.com/orbit-w/orbit/app/proto/mmeb\x06proto3"

var (
	file_modules_proto_rawDescOnce sync.Once
	file_modules_proto_rawDescData []byte
)

func file_modules_proto_rawDescGZIP() []byte {
	file_modules_proto_rawDescOnce.Do(func() {
		file_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_proto_rawDesc), len(file_modules_proto_rawDesc)))
	})
	return file_modules_proto_rawDescData
}

var file_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_proto_goTypes = []any{
	(*HeroModule)(nil),            // 0: MME.HeroModule
	(*HeroMechanism)(nil),         // 1: MME.HeroMechanism
	(*LevelUpMechanism)(nil),      // 2: MME.LevelUpMechanism
	(*ManualUnlockMechanism)(nil), // 3: MME.ManualUnlockMechanism
	(*WearMechanism)(nil),         // 4: MME.WearMechanism
}
var file_modules_proto_depIdxs = []int32{
	1, // 0: MME.HeroModule.Base:type_name -> MME.HeroMechanism
	2, // 1: MME.HeroModule.LevelUp:type_name -> MME.LevelUpMechanism
	3, // 2: MME.HeroModule.TalentUnlock:type_name -> MME.ManualUnlockMechanism
	4, // 3: MME.HeroModule.SkinWear:type_name -> MME.WearMechanism
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_modules_proto_init() }
func file_modules_proto_init() {
	if File_modules_proto != nil {
		return
	}
	file_mechanisms_proto_init()
	file_modules_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_proto_rawDesc), len(file_modules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_proto_goTypes,
		DependencyIndexes: file_modules_proto_depIdxs,
		MessageInfos:      file_modules_proto_msgTypes,
	}.Build()
	File_modules_proto = out.File
	file_modules_proto_goTypes = nil
	file_modules_proto_depIdxs = nil
}
