// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protocol/notify.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_protocol_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_protocol_notify_proto_rawDescGZIP(), []int{0}
}

type Notify_BeAttacked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify_BeAttacked) Reset() {
	*x = Notify_BeAttacked{}
	mi := &file_protocol_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify_BeAttacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_BeAttacked) ProtoMessage() {}

func (x *Notify_BeAttacked) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_BeAttacked.ProtoReflect.Descriptor instead.
func (*Notify_BeAttacked) Descriptor() ([]byte, []int) {
	return file_protocol_notify_proto_rawDescGZIP(), []int{0, 0}
}

type Notify_ExpChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify_ExpChange) Reset() {
	*x = Notify_ExpChange{}
	mi := &file_protocol_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify_ExpChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_ExpChange) ProtoMessage() {}

func (x *Notify_ExpChange) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_ExpChange.ProtoReflect.Descriptor instead.
func (*Notify_ExpChange) Descriptor() ([]byte, []int) {
	return file_protocol_notify_proto_rawDescGZIP(), []int{0, 1}
}

var File_protocol_notify_proto protoreflect.FileDescriptor

const file_protocol_notify_proto_rawDesc = "" +
	"\n" +
	"\x15protocol/notify.proto\x12\x04Core\x1a\x16protocol/structs.proto\x1a\x15protocol/common.proto\"#\n" +
	"\x06Notify\x1a\f\n" +
	"\n" +
	"BeAttacked\x1a\v\n" +
	"\tExpChangeB\aZ\x05./mmeb\x06proto3"

var (
	file_protocol_notify_proto_rawDescOnce sync.Once
	file_protocol_notify_proto_rawDescData []byte
)

func file_protocol_notify_proto_rawDescGZIP() []byte {
	file_protocol_notify_proto_rawDescOnce.Do(func() {
		file_protocol_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_notify_proto_rawDesc), len(file_protocol_notify_proto_rawDesc)))
	})
	return file_protocol_notify_proto_rawDescData
}

var file_protocol_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_notify_proto_goTypes = []any{
	(*Notify)(nil),            // 0: Core.Notify
	(*Notify_BeAttacked)(nil), // 1: Core.Notify.BeAttacked
	(*Notify_ExpChange)(nil),  // 2: Core.Notify.ExpChange
}
var file_protocol_notify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_notify_proto_init() }
func file_protocol_notify_proto_init() {
	if File_protocol_notify_proto != nil {
		return
	}
	file_protocol_structs_proto_init()
	file_protocol_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_notify_proto_rawDesc), len(file_protocol_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_notify_proto_goTypes,
		DependencyIndexes: file_protocol_notify_proto_depIdxs,
		MessageInfos:      file_protocol_notify_proto_msgTypes,
	}.Build()
	File_protocol_notify_proto = out.File
	file_protocol_notify_proto_goTypes = nil
	file_protocol_notify_proto_depIdxs = nil
}
