// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protocol/request.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protocol_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protocol_request_proto_rawDescGZIP(), []int{0}
}

type Request_AskLevelUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_AskLevelUp) Reset() {
	*x = Request_AskLevelUp{}
	mi := &file_protocol_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_AskLevelUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_AskLevelUp) ProtoMessage() {}

func (x *Request_AskLevelUp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_AskLevelUp.ProtoReflect.Descriptor instead.
func (*Request_AskLevelUp) Descriptor() ([]byte, []int) {
	return file_protocol_request_proto_rawDescGZIP(), []int{0, 0}
}

type Request_SearchBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchBook) Reset() {
	*x = Request_SearchBook{}
	mi := &file_protocol_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchBook) ProtoMessage() {}

func (x *Request_SearchBook) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchBook.ProtoReflect.Descriptor instead.
func (*Request_SearchBook) Descriptor() ([]byte, []int) {
	return file_protocol_request_proto_rawDescGZIP(), []int{0, 1}
}

type Request_HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_HeartBeat) Reset() {
	*x = Request_HeartBeat{}
	mi := &file_protocol_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_HeartBeat) ProtoMessage() {}

func (x *Request_HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_HeartBeat.ProtoReflect.Descriptor instead.
func (*Request_HeartBeat) Descriptor() ([]byte, []int) {
	return file_protocol_request_proto_rawDescGZIP(), []int{0, 2}
}

type Request_RequestB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_RequestB) Reset() {
	*x = Request_RequestB{}
	mi := &file_protocol_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_RequestB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_RequestB) ProtoMessage() {}

func (x *Request_RequestB) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_RequestB.ProtoReflect.Descriptor instead.
func (*Request_RequestB) Descriptor() ([]byte, []int) {
	return file_protocol_request_proto_rawDescGZIP(), []int{0, 3}
}

type Request_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_Rsp) Reset() {
	*x = Request_Rsp{}
	mi := &file_protocol_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Rsp) ProtoMessage() {}

func (x *Request_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Rsp.ProtoReflect.Descriptor instead.
func (*Request_Rsp) Descriptor() ([]byte, []int) {
	return file_protocol_request_proto_rawDescGZIP(), []int{0, 4}
}

var File_protocol_request_proto protoreflect.FileDescriptor

const file_protocol_request_proto_rawDesc = "" +
	"\n" +
	"\x16protocol/request.proto\x12\x04Core\x1a\x16protocol/structs.proto\x1a\x15protocol/common.proto\"E\n" +
	"\aRequest\x1a\f\n" +
	"\n" +
	"AskLevelUp\x1a\f\n" +
	"\n" +
	"SearchBook\x1a\v\n" +
	"\tHeartBeat\x1a\n" +
	"\n" +
	"\bRequestB\x1a\x05\n" +
	"\x03RspB\aZ\x05./mmeb\x06proto3"

var (
	file_protocol_request_proto_rawDescOnce sync.Once
	file_protocol_request_proto_rawDescData []byte
)

func file_protocol_request_proto_rawDescGZIP() []byte {
	file_protocol_request_proto_rawDescOnce.Do(func() {
		file_protocol_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_request_proto_rawDesc), len(file_protocol_request_proto_rawDesc)))
	})
	return file_protocol_request_proto_rawDescData
}

var file_protocol_request_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protocol_request_proto_goTypes = []any{
	(*Request)(nil),            // 0: Core.Request
	(*Request_AskLevelUp)(nil), // 1: Core.Request.AskLevelUp
	(*Request_SearchBook)(nil), // 2: Core.Request.SearchBook
	(*Request_HeartBeat)(nil),  // 3: Core.Request.HeartBeat
	(*Request_RequestB)(nil),   // 4: Core.Request.RequestB
	(*Request_Rsp)(nil),        // 5: Core.Request.Rsp
}
var file_protocol_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_request_proto_init() }
func file_protocol_request_proto_init() {
	if File_protocol_request_proto != nil {
		return
	}
	file_protocol_structs_proto_init()
	file_protocol_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_request_proto_rawDesc), len(file_protocol_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_request_proto_goTypes,
		DependencyIndexes: file_protocol_request_proto_depIdxs,
		MessageInfos:      file_protocol_request_proto_msgTypes,
	}.Build()
	File_protocol_request_proto = out.File
	file_protocol_request_proto_goTypes = nil
	file_protocol_request_proto_depIdxs = nil
}
