// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protocol/structs.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protocol_structs_proto protoreflect.FileDescriptor

const file_protocol_structs_proto_rawDesc = "" +
	"\n" +
	"\x16protocol/structs.proto\x12\x04Core\x1a\x15protocol/common.protoB\aZ\x05./mmeb\x06proto3"

var file_protocol_structs_proto_goTypes = []any{}
var file_protocol_structs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_structs_proto_init() }
func file_protocol_structs_proto_init() {
	if File_protocol_structs_proto != nil {
		return
	}
	file_protocol_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_structs_proto_rawDesc), len(file_protocol_structs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_structs_proto_goTypes,
		DependencyIndexes: file_protocol_structs_proto_depIdxs,
	}.Build()
	File_protocol_structs_proto = out.File
	file_protocol_structs_proto_goTypes = nil
	file_protocol_structs_proto_depIdxs = nil
}
