// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme"
	"gitee.com/orbit-w/orbit/internal/game/mme_agent/imodels"
	"gitee.com/orbit-w/orbit/internal/game/mme_agent/managers"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// PlayerEntityAgent PlayerEntity Agent 实现
type PlayerEntityAgent struct {
	entityWrapper *mme.PlayerEntityWrapper

	heroManagerLogic imodels.IHeroManagerLogic
}

func NewPlayerEntityAgent() *PlayerEntityAgent {
	return &PlayerEntityAgent{
		entityWrapper: mme.NewPlayerEntityWrapper(),
	}
}

func (a *PlayerEntityAgent) GetEntity() mme.IEntity {
	return a.entityWrapper
}

func (a *PlayerEntityAgent) GetHeroManagerLogic() imodels.IHeroManagerLogic {
	if a.heroManagerLogic == nil {
		a.heroManagerLogic = managers.NewHeroManagerLogic(a.entityWrapper.GetHeroManager())
	}
	return a.heroManagerLogic
}

func (a *PlayerEntityAgent) OnLoad(raw bson.Raw, new bool) error {
	if err := a.entityWrapper.Load(raw); err != nil {
		return err
	}

	if err := a.GetHeroManagerLogic().OnLoad(new); err != nil {
		return err
	}
	return nil
}

func (a *PlayerEntityAgent) OnSave() error {
	if err := a.GetHeroManagerLogic().OnSave(); err != nil {
		return err
	}
	return nil
}
