// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: core.proto

package core

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type Notify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *string                `protobuf:"bytes,1,opt,name=Content,proto3,oneof" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *Book) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type OK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OK) Reset() {
	*x = OK{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OK) ProtoMessage() {}

func (x *OK) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OK.ProtoReflect.Descriptor instead.
func (*OK) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        *string                `protobuf:"bytes,1,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type MMELocation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityId       *int64                 `protobuf:"varint,1,opt,name=EntityId,proto3,oneof" json:"EntityId,omitempty"`
	ModuleId       *int32                 `protobuf:"varint,2,opt,name=ModuleId,proto3,oneof" json:"ModuleId,omitempty"`
	MechanismIndex *int32                 `protobuf:"varint,3,opt,name=MechanismIndex,proto3,oneof" json:"MechanismIndex,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MMELocation) Reset() {
	*x = MMELocation{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MMELocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MMELocation) ProtoMessage() {}

func (x *MMELocation) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MMELocation.ProtoReflect.Descriptor instead.
func (*MMELocation) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *MMELocation) GetEntityId() int64 {
	if x != nil && x.EntityId != nil {
		return *x.EntityId
	}
	return 0
}

func (x *MMELocation) GetModuleId() int32 {
	if x != nil && x.ModuleId != nil {
		return *x.ModuleId
	}
	return 0
}

func (x *MMELocation) GetMechanismIndex() int32 {
	if x != nil && x.MechanismIndex != nil {
		return *x.MechanismIndex
	}
	return 0
}

type Coord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *int32                 `protobuf:"varint,1,opt,name=X,proto3,oneof" json:"X,omitempty"`
	Y             *int32                 `protobuf:"varint,2,opt,name=Y,proto3,oneof" json:"Y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coord) Reset() {
	*x = Coord{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *Coord) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Coord) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type Request_SearchBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *string                `protobuf:"bytes,1,opt,name=Query,proto3,oneof" json:"Query,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,2,opt,name=PageNumber,proto3,oneof" json:"PageNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchBook) Reset() {
	*x = Request_SearchBook{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchBook) ProtoMessage() {}

func (x *Request_SearchBook) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchBook.ProtoReflect.Descriptor instead.
func (*Request_SearchBook) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_SearchBook) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *Request_SearchBook) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

type Request_HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_HeartBeat) Reset() {
	*x = Request_HeartBeat{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_HeartBeat) ProtoMessage() {}

func (x *Request_HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_HeartBeat.ProtoReflect.Descriptor instead.
func (*Request_HeartBeat) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0, 1}
}

type Request_SearchBook_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Book                  `protobuf:"bytes,1,opt,name=Result,proto3,oneof" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchBook_Rsp) Reset() {
	*x = Request_SearchBook_Rsp{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchBook_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchBook_Rsp) ProtoMessage() {}

func (x *Request_SearchBook_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchBook_Rsp.ProtoReflect.Descriptor instead.
func (*Request_SearchBook_Rsp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_SearchBook_Rsp) GetResult() *Book {
	if x != nil {
		return x.Result
	}
	return nil
}

type Notify_BeAttacked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurHp         *int32                 `protobuf:"varint,1,opt,name=CurHp,proto3,oneof" json:"CurHp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify_BeAttacked) Reset() {
	*x = Notify_BeAttacked{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify_BeAttacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_BeAttacked) ProtoMessage() {}

func (x *Notify_BeAttacked) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_BeAttacked.ProtoReflect.Descriptor instead.
func (*Notify_BeAttacked) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Notify_BeAttacked) GetCurHp() int32 {
	if x != nil && x.CurHp != nil {
		return *x.CurHp
	}
	return 0
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04Core\"\xb9\x01\n" +
	"\aRequest\x1a\xa0\x01\n" +
	"\n" +
	"SearchBook\x12\x19\n" +
	"\x05Query\x18\x01 \x01(\tH\x00R\x05Query\x88\x01\x01\x12#\n" +
	"\n" +
	"PageNumber\x18\x02 \x01(\x05H\x01R\n" +
	"PageNumber\x88\x01\x01\x1a9\n" +
	"\x03Rsp\x12'\n" +
	"\x06Result\x18\x01 \x01(\v2\n" +
	".Core.BookH\x00R\x06Result\x88\x01\x01B\t\n" +
	"\a_ResultB\b\n" +
	"\x06_QueryB\r\n" +
	"\v_PageNumber\x1a\v\n" +
	"\tHeartBeat\";\n" +
	"\x06Notify\x1a1\n" +
	"\n" +
	"BeAttacked\x12\x19\n" +
	"\x05CurHp\x18\x01 \x01(\x05H\x00R\x05CurHp\x88\x01\x01B\b\n" +
	"\x06_CurHp\"1\n" +
	"\x04Book\x12\x1d\n" +
	"\aContent\x18\x01 \x01(\tH\x00R\aContent\x88\x01\x01B\n" +
	"\n" +
	"\b_Content\"\x04\n" +
	"\x02OK\"/\n" +
	"\x05Error\x12\x1b\n" +
	"\x06Reason\x18\x01 \x01(\tH\x00R\x06Reason\x88\x01\x01B\t\n" +
	"\a_Reason\"\xa9\x01\n" +
	"\vMMELocation\x12\x1f\n" +
	"\bEntityId\x18\x01 \x01(\x03H\x00R\bEntityId\x88\x01\x01\x12\x1f\n" +
	"\bModuleId\x18\x02 \x01(\x05H\x01R\bModuleId\x88\x01\x01\x12+\n" +
	"\x0eMechanismIndex\x18\x03 \x01(\x05H\x02R\x0eMechanismIndex\x88\x01\x01B\v\n" +
	"\t_EntityIdB\v\n" +
	"\t_ModuleIdB\x11\n" +
	"\x0f_MechanismIndex\"9\n" +
	"\x05Coord\x12\x11\n" +
	"\x01X\x18\x01 \x01(\x05H\x00R\x01X\x88\x01\x01\x12\x11\n" +
	"\x01Y\x18\x02 \x01(\x05H\x01R\x01Y\x88\x01\x01B\x04\n" +
	"\x02_XB\x04\n" +
	"\x02_YB(Z&gitee.com/orbit-w/orbit/app/proto/coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_proto_goTypes = []any{
	(*Request)(nil),                // 0: Core.Request
	(*Notify)(nil),                 // 1: Core.Notify
	(*Book)(nil),                   // 2: Core.Book
	(*OK)(nil),                     // 3: Core.OK
	(*Error)(nil),                  // 4: Core.Error
	(*MMELocation)(nil),            // 5: Core.MMELocation
	(*Coord)(nil),                  // 6: Core.Coord
	(*Request_SearchBook)(nil),     // 7: Core.Request.SearchBook
	(*Request_HeartBeat)(nil),      // 8: Core.Request.HeartBeat
	(*Request_SearchBook_Rsp)(nil), // 9: Core.Request.SearchBook.Rsp
	(*Notify_BeAttacked)(nil),      // 10: Core.Notify.BeAttacked
}
var file_core_proto_depIdxs = []int32{
	2, // 0: Core.Request.SearchBook.Rsp.Result:type_name -> Core.Book
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_core_proto_msgTypes[2].OneofWrappers = []any{}
	file_core_proto_msgTypes[4].OneofWrappers = []any{}
	file_core_proto_msgTypes[5].OneofWrappers = []any{}
	file_core_proto_msgTypes[6].OneofWrappers = []any{}
	file_core_proto_msgTypes[7].OneofWrappers = []any{}
	file_core_proto_msgTypes[9].OneofWrappers = []any{}
	file_core_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
