syntax = "proto3";

import "Common.proto";

package MME;

// 升级机制
message LevelUpMechanism {
    // 当前等级
    optional int32 CurLevel = 1;
    // 当前经验值
    optional int32 CurExp = 2;
    // 走哪套升级配置
    optional int32 ConfId = 3;
}


// 英雄机制
message HeroMechanism {
    // 英雄配置ID
    optional int32 ConfId = 1;
    // 玩家获得英雄的时间
    optional int64 CreateTime = 2;
    // 英雄被使用次数
    optional int32 UseTimes = 3;
}


// 手动解锁机制
message ManualUnlockMechanism {
    // 解锁状态
    map<int32, bool> UnlockMap = 1;
    repeated UnlockMap_XXXMapChangeRecord UnlockMap_XXXChangeList = 1001;  message UnlockMap_XXXMapChangeRecord { int32 key = 1; bool value = 2; bool isDelete = 3; }

}


// 穿戴机制
message WearMechanism {
    // 穿戴状态
    map<int32, int32> WearMap = 1;
    repeated WearMap_XXXMapChangeRecord WearMap_XXXChangeList = 1001;  message WearMap_XXXMapChangeRecord { int32 key = 1; int32 value = 2; bool isDelete = 3; }

    // 走哪套穿戴配置
    optional int32 ConfId = 2;
    // 测试
    optional Chicken Chicken = 3;
    repeated Chicken ChickenList = 4;
    repeated ChickenList_XXXListChangeRecord ChickenList_XXXChangeList = 1004;
  message ChickenList_XXXListChangeRecord {
    int32 Index = 1;
    Chicken Value = 2;
    uint32 OptionType = 3;
  }

    optional Fish Fish = 5;
}


message Chicken {
    optional int32 EggCnt = 1;
    // 鸡蛋
    map<int32, int32> EggMap = 2;
    repeated EggMap_XXXMapChangeRecord EggMap_XXXChangeList = 1002;  message EggMap_XXXMapChangeRecord { int32 key = 1; int32 value = 2; bool isDelete = 3; }

}


