// Code generated by blueprint PB Factory generator. DO NOT EDIT.
package pb

import (
	"fmt"

	"google.golang.org/protobuf/proto"

	"gitee.com/orbit-w/orbit/pkg/proto/core"
	"gitee.com/orbit-w/orbit/pkg/proto/mme"
	"gitee.com/orbit-w/orbit/pkg/proto/play"
)

type pbFactory func() proto.Message

var (
	pbFactories = make(map[uint32]pbFactory)
)

func init() {
	RegisterPBFactory(PID_Request_AskLevelUp, func() proto.Message {
		return &mme.Request_AskLevelUp{}
	})
	RegisterPBFactory(PID_Request_HeartBeat, func() proto.Message {
		return &core.Request_HeartBeat{}
	})
	RegisterPBFactory(PID_Request_LoginRequest, func() proto.Message {
		return &play.Request_LoginRequest{}
	})
	RegisterPBFactory(PID_Request_SetEntityRequest, func() proto.Message {
		return &core.Request_SetEntityRequest{}
	})
}

func RegisterPBFactory(pid uint32, factory pbFactory) {
	if _, ok := pbFactories[pid]; ok {
		panic(fmt.Sprintf("create pb from request already registered for pid: %d", pid))
	}
	pbFactories[pid] = factory
}

func GetPBFactory(pid uint32) pbFactory {
	return pbFactories[pid]
}
