// Code generated by blueprint Ref Extractor generator. DO NOT EDIT.
package pb

import (
	"fmt"

	"google.golang.org/protobuf/proto"

	"gitee.com/orbit-w/orbit/pkg/proto/core"
	"gitee.com/orbit-w/orbit/pkg/proto/mme"
	"gitee.com/orbit-w/orbit/pkg/proto/play"
)

type ExtractRefsFromRequest func(req proto.Message) ([]*mme.EntityRef, error)

var (
	extractRefsFromRequests = make(map[uint32]ExtractRefsFromRequest)
)

func init() {
	RegisterRefExtract(PID_Request_LoginRequest, func(request proto.Message) ([]*mme.EntityRef, error) {
		req := request.(*play.Request_LoginRequest)
		refs := make([]*mme.EntityRef, 0)
		if req.PlayerEntityRef != nil {
			refs = append(refs, req.PlayerEntityRef)
		}
		return refs, nil
	})

	RegisterRefExtract(PID_Request_SetEntityRequest, func(request proto.Message) ([]*mme.EntityRef, error) {
		req := request.(*core.Request_SetEntityRequest)
		refs := make([]*mme.EntityRef, 0)
		if req.EntityRef != nil {
			refs = append(refs, req.EntityRef)
		}
		return refs, nil
	})

}

func RegisterRefExtract(pid uint32, factory ExtractRefsFromRequest) {
	if _, ok := extractRefsFromRequests[pid]; ok {
		panic(fmt.Sprintf("ref factory already registered for pid: %d", pid))
	}
	extractRefsFromRequests[pid] = factory
}

// GetExtract 获取Ref提取器
func GetExtract(pid uint32) ExtractRefsFromRequest {
	return extractRefsFromRequests[pid]
}
