// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	mmeobj "gitee.com/orbit-w/orbit/internal/game/mme"
	"gitee.com/orbit-w/orbit/pkg/proto/mme"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type IEntity interface {
	GetId() int64
	GetEntityType() mme.EntityType
	GetEntityWrapper() mmeobj.IEntityWrapper
	OnLoad(raw bson.Raw, new bool) error
	OnSave() error
	OnLogin() error
	OnLogout() error
}

type EntityFactory func() IEntity

var (
	mapEntityFactories = make(map[mme.EntityType]EntityFactory)
)

func RegisterEntityFactory(entityType mme.EntityType, factory EntityFactory) {
	mapEntityFactories[entityType] = factory
}

func GetEntityFactory(entityType mme.EntityType) EntityFactory {
	factory, ok := mapEntityFactories[entityType]
	if !ok {
		return nil
	}
	return factory
}
