// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme"

	"gitee.com/orbit-w/orbit/internal/game/mme_logic/imodels"
	"gitee.com/orbit-w/orbit/internal/game/mme_logic/mechanisms"
)

// HeroModuleLogicImpl HeroModule Logic 实现
type HeroModuleAgentImpl struct {
	wrapper *mme.HeroModuleWrapper

	baseLogic    imodels.IHeroMechanismLogic
	levelUpLogic imodels.ILevelUpMechanismLogic
}

// NewHeroModuleLogic 创建 HeroModule Logic
func NewHeroModuleLogic(wrapper *mme.HeroModuleWrapper) IHeroModuleAgent {
	return &HeroModuleAgentImpl{
		wrapper: wrapper,
	}
}

// GetWrapper 获取 Wrapper
func (m *HeroModuleAgentImpl) GetWrapper() any {
	return m.wrapper
}

// OnLoad 加载回调
func (m *HeroModuleAgentImpl) OnLoad(new bool) error {
	if err := CallOnLoad(m.GetHeroMechanismModel(), new); err != nil {
		return err
	}

	if err := CallOnLoad(m.GetLevelUpMechanismLogic(), new); err != nil {
		return err
	}
	return nil
}

// OnSave 保存回调
func (m *HeroModuleAgentImpl) OnSave() error {
	if err := CallOnSave(m.GetHeroMechanismModel()); err != nil {
		return err
	}

	if err := CallOnSave(m.GetLevelUpMechanismLogic()); err != nil {
		return err
	}
	return nil
}

// OnLogin 登录回调
func (m *HeroModuleAgentImpl) OnLogin() error {
	if err := CallOnLogin(m.GetHeroMechanismModel()); err != nil {
		return err
	}
	if err := CallOnLogin(m.GetLevelUpMechanismLogic()); err != nil {
		return err
	}
	return nil
}

// OnLogout 登出回调
func (m *HeroModuleAgentImpl) OnLogout() error {
	if err := CallOnLogout(m.GetHeroMechanismModel()); err != nil {
		return err
	}
	if err := CallOnLogout(m.GetLevelUpMechanismLogic()); err != nil {
		return err
	}
	return nil
}

func (m *HeroModuleAgentImpl) GetHeroMechanismModel() imodels.IHeroMechanismLogic {
	if m.baseLogic == nil {
		m.baseLogic = mechanisms.NewHeroMechanismLogic(m.wrapper.GetBase())
	}
	return m.baseLogic
}

func (m *HeroModuleAgentImpl) GetLevelUpMechanismLogic() imodels.ILevelUpMechanismLogic {
	if m.levelUpLogic == nil {
		m.levelUpLogic = mechanisms.NewLevelUpMechanismLogic(m.wrapper.GetLevelUp())
	}
	return m.levelUpLogic
}
