// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme"
	"gitee.com/orbit-w/orbit/internal/game/mme_logic/imodels"
	"gitee.com/orbit-w/orbit/internal/game/mme_logic/managers"
	"gitee.com/orbit-w/orbit/lib/container"
)

type HeroManagerAgentImpl struct {
	imodels.IHeroManagerLogic
	wrapper *mme.HeroManagerWrapper

	heroMapContainer      *container.ModuleMapContainer[int64, *mme.HeroModule, *mme.HeroModuleWrapper, IHeroModuleAgent]
	singleHeroModuleAgent IHeroModuleAgent
}

func NewHeroManagerAgent(wrapper *mme.HeroManagerWrapper) IHeroManagerAgent {
	ins := &HeroManagerAgentImpl{
		wrapper:           wrapper,
		IHeroManagerLogic: managers.NewHeroManagerLogic(wrapper),
		heroMapContainer: container.NewModuleMapContainer(
			wrapper.GetHeroMap(),
			NewHeroModuleLogic,
		),
	}
	return ins
}

func (m *HeroManagerAgentImpl) GetWrapper() any {
	return m.wrapper
}

func (m *HeroManagerAgentImpl) OnLoad(new bool) error {
	var err error
	m.heroMapContainer.Range(func(key int64, agent IHeroModuleAgent) bool {
		if err = CallOnLoad(agent, new); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnLoad(m.GetSingleHeroModule(), new); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) OnSave() error {
	var err error
	m.heroMapContainer.Range(func(key int64, agent IHeroModuleAgent) bool {
		if err = CallOnSave(agent); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnSave(m.GetSingleHeroModule()); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) OnLogin() error {
	var err error
	m.heroMapContainer.Range(func(key int64, agent IHeroModuleAgent) bool {
		if err = CallOnLogin(agent); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnLogin(m.GetSingleHeroModule()); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) OnLogout() error {
	var err error
	m.heroMapContainer.Range(func(key int64, agent IHeroModuleAgent) bool {
		if err = CallOnLogout(agent); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnLogout(m.GetSingleHeroModule()); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) HeroMap_GetModule(key int64) (IHeroModuleAgent, bool) {
	logic, exists := m.heroMapContainer.Get(key)
	return logic, exists
}

func (m *HeroManagerAgentImpl) GetSingleHeroModule() IHeroModuleAgent {
	if m.singleHeroModuleAgent == nil {
		wrapper := m.wrapper.GetSingleHeroModule()
		if wrapper == nil {
			return nil
		}
		m.singleHeroModuleAgent = NewHeroModuleLogic(wrapper)
	}
	return m.singleHeroModuleAgent
}
