// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme"

	"gitee.com/orbit-w/orbit/internal/game/mme_logic/imodels"
	"gitee.com/orbit-w/orbit/lib/container"

	"gitee.com/orbit-w/orbit/internal/game/mme_logic/managers"
)

type HeroManagerAgentImpl struct {
	imodels.IHeroManagerLogic
	wrapper *mme.HeroManagerWrapper

	heroModuleLogics *container.ModuleMapContainer[int64, *mme.HeroModule, *mme.HeroModuleWrapper, IHeroModuleAgent]
	singleHeroModule IHeroModuleAgent
}

// NewHeroManagerAgent 创建 HeroManager Agent
func NewHeroManagerAgent(wrapper *mme.HeroManagerWrapper) IHeroManagerAgent {
	ins := &HeroManagerAgentImpl{
		wrapper:           wrapper,
		IHeroManagerLogic: managers.NewHeroManagerLogic(wrapper),
		heroModuleLogics: container.NewModuleMapContainer(
			wrapper.GetHeroMap(),
			NewHeroModuleLogic,
		),
	}

	return ins
}

// GetWrapper 获取 Wrapper
func (m *HeroManagerAgentImpl) GetWrapper() any {
	return m.wrapper
}

func (m *HeroManagerAgentImpl) OnLoad(new bool) error {
	var err error
	m.heroModuleLogics.Range(func(key int64, logic IHeroModuleAgent) bool {
		if err := CallOnLoad(logic, new); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnLoad(m.GetSingleHeroModule(), new); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) OnSave() error {
	var err error
	m.heroModuleLogics.Range(func(key int64, logic IHeroModuleAgent) bool {
		if err := CallOnSave(logic); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}
	if err := CallOnSave(m.GetSingleHeroModule()); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) OnLogin() error {
	var err error
	m.heroModuleLogics.Range(func(key int64, logic IHeroModuleAgent) bool {
		if err := CallOnLogin(logic); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnLogin(m.GetSingleHeroModule()); err != nil {
		return err
	}
	return nil
}

func (m *HeroManagerAgentImpl) OnLogout() error {
	var err error
	m.heroModuleLogics.Range(func(key int64, logic IHeroModuleAgent) bool {
		if err := CallOnLogout(logic); err != nil {
			return false
		}
		return true
	})
	if err != nil {
		return err
	}

	if err := CallOnLogout(m.GetSingleHeroModule()); err != nil {
		return err
	}
	return nil
}
func (m *HeroManagerAgentImpl) HeroMap_GetModule(heroId int64) (IHeroModuleAgent, bool) {
	logic, exists := m.heroModuleLogics.Get(heroId)
	return logic, exists
}

func (m *HeroManagerAgentImpl) GetSingleHeroModule() IHeroModuleAgent {
	if m.singleHeroModule == nil {
		wrapper := m.wrapper.GetSingleHeroModule()
		if wrapper == nil {
			return nil
		}
		m.singleHeroModule = NewHeroModuleLogic(wrapper)
	}
	return m.singleHeroModule
}
