// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme"
	"gitee.com/orbit-w/orbit/internal/game/mme_logic/imodels"
	"gitee.com/orbit-w/orbit/internal/game/mme_logic/mechanisms"
)

type HeroModuleAgentImpl struct {
	wrapper *mme.HeroModuleWrapper

	baseLogic         imodels.IHeroMechanismLogic
	levelUpLogic      imodels.ILevelUpMechanismLogic
	talentUnlockLogic imodels.IManualUnlockMechanismLogic
	skinWearLogic     imodels.IWearMechanismLogic
}

func NewHeroModuleAgent(wrapper *mme.HeroModuleWrapper) IHeroModuleAgent {
	return &HeroModuleAgentImpl{
		wrapper: wrapper,
	}
}

func (m *HeroModuleAgentImpl) GetWrapper() any {
	return m.wrapper
}

func (m *HeroModuleAgentImpl) OnLoad(new bool) error {
	if err := CallOnLoad(m.GetHeroMechanismLogic(), new); err != nil {
		return err
	}
	if err := CallOnLoad(m.GetLevelUpMechanismLogic(), new); err != nil {
		return err
	}
	if err := CallOnLoad(m.GetManualUnlockMechanismLogic(), new); err != nil {
		return err
	}
	if err := CallOnLoad(m.GetWearMechanismLogic(), new); err != nil {
		return err
	}
	return nil
}

func (m *HeroModuleAgentImpl) OnSave() error {
	if err := CallOnSave(m.GetHeroMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnSave(m.GetLevelUpMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnSave(m.GetManualUnlockMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnSave(m.GetWearMechanismLogic()); err != nil {
		return err
	}
	return nil
}

func (m *HeroModuleAgentImpl) OnLogin() error {
	if err := CallOnLogin(m.GetHeroMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnLogin(m.GetLevelUpMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnLogin(m.GetManualUnlockMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnLogin(m.GetWearMechanismLogic()); err != nil {
		return err
	}
	return nil
}

func (m *HeroModuleAgentImpl) OnLogout() error {
	if err := CallOnLogout(m.GetHeroMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnLogout(m.GetLevelUpMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnLogout(m.GetManualUnlockMechanismLogic()); err != nil {
		return err
	}
	if err := CallOnLogout(m.GetWearMechanismLogic()); err != nil {
		return err
	}
	return nil
}

func (m *HeroModuleAgentImpl) GetHeroMechanismLogic() imodels.IHeroMechanismLogic {
	if m.baseLogic == nil {
		m.baseLogic = mechanisms.NewHeroMechanismLogic(m.wrapper.GetBase())
	}
	return m.baseLogic
}

func (m *HeroModuleAgentImpl) GetLevelUpMechanismLogic() imodels.ILevelUpMechanismLogic {
	if m.levelUpLogic == nil {
		m.levelUpLogic = mechanisms.NewLevelUpMechanismLogic(m.wrapper.GetLevelUp())
	}
	return m.levelUpLogic
}

func (m *HeroModuleAgentImpl) GetManualUnlockMechanismLogic() imodels.IManualUnlockMechanismLogic {
	if m.talentUnlockLogic == nil {
		m.talentUnlockLogic = mechanisms.NewManualUnlockMechanismLogic(m.wrapper.GetTalentUnlock())
	}
	return m.talentUnlockLogic
}

func (m *HeroModuleAgentImpl) GetWearMechanismLogic() imodels.IWearMechanismLogic {
	if m.skinWearLogic == nil {
		m.skinWearLogic = mechanisms.NewWearMechanismLogic(m.wrapper.GetSkinWear())
	}
	return m.skinWearLogic
}
