// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme_logic/imodels"
)

type IBaseAgent interface {
	GetWrapper() any
}

type IHeroManagerAgent interface {
	IBaseAgent
	imodels.IHeroManagerLogic
}

type IHeroModuleAgent interface {
	IBaseAgent
	GetHeroMechanismLogic() imodels.IHeroMechanismLogic
	GetLevelUpMechanismLogic() imodels.ILevelUpMechanismLogic
	GetManualUnlockMechanismLogic() imodels.IManualUnlockMechanismLogic
	GetWearMechanismLogic() imodels.IWearMechanismLogic
}
