// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package mme_agent

import (
	mmeobj "gitee.com/orbit-w/orbit/internal/game/mme"
	"gitee.com/orbit-w/orbit/pkg/proto/mme"

	"go.mongodb.org/mongo-driver/v2/bson"
)

func init() {
	RegisterEntityFactory(mme.EntityType_PlayerEntityType, func() IEntity {
		return NewPlayerEntity()
	})
}

// PlayerEntityAgent PlayerEntity Agent 实现
type PlayerEntityImpl struct {
	entityWrapper *mmeobj.PlayerEntityWrapper

	heroManagerAgent IHeroManagerAgent
}

func NewPlayerEntity() *PlayerEntityImpl {
	return &PlayerEntityImpl{
		entityWrapper: mmeobj.NewPlayerEntityWrapper(),
	}
}

func (a *PlayerEntityImpl) GetId() int64 {
	return a.entityWrapper.GetXXXId()
}

func (a *PlayerEntityImpl) GetEntityType() mme.EntityType {
	return a.entityWrapper.GetEntityType()
}

func (a *PlayerEntityImpl) GetEntityWrapper() mmeobj.IEntityWrapper {
	return a.entityWrapper
}

func (a *PlayerEntityImpl) GetHeroManagerAgent() IHeroManagerAgent {
	if a.heroManagerAgent == nil {
		a.heroManagerAgent = NewHeroManagerAgent(a.entityWrapper.GetHeroManager())
	}
	return a.heroManagerAgent
}

// OnLoad 加载回调
func (a *PlayerEntityImpl) OnLoad(raw bson.Raw, new bool) error {
	if err := a.entityWrapper.Load(raw); err != nil {
		return err
	}

	if err := CallOnLoad(a.GetHeroManagerAgent(), new); err != nil {
		return err
	}
	return nil
}

// OnSave 保存回调
func (a *PlayerEntityImpl) OnSave() error {
	if err := CallOnSave(a.GetHeroManagerAgent()); err != nil {
		return err
	}
	return nil
}

// OnLogin 登录回调
func (a *PlayerEntityImpl) OnLogin() error {
	if err := CallOnLogin(a.GetHeroManagerAgent()); err != nil {
		return err
	}
	return nil
}

// OnLogout 登出回调
func (a *PlayerEntityImpl) OnLogout() error {
	if err := CallOnLogout(a.GetHeroManagerAgent()); err != nil {
		return err
	}
	return nil
}
