// Code generated by blueprint_gen. DO NOT EDIT.
// This file is automatically generated. To regenerate, run: blueprintgen

package agent

import (
	"gitee.com/orbit-w/orbit/internal/game/mme"
	"gitee.com/orbit-w/orbit/internal/game/mme_agent/imodels"
	"gitee.com/orbit-w/orbit/internal/game/mme_agent/managers"
)

// PlayerEntityAgent PlayerEntity Agent 实现
type PlayerEntityAgent struct {
	entityWrapper *mme.PlayerEntityWrapper

	heroManagerLogic imodels.IHeroManagerLogic
}

func NewPlayerEntityAgent(entityWrapper *mme.PlayerEntityWrapper) *PlayerEntityAgent {
	return &PlayerEntityAgent{
		entityWrapper: entityWrapper,
	}
}

func (a *PlayerEntityAgent) GetHeroManagerLogic() imodels.IHeroManagerLogic {
	if a.heroManagerLogic == nil {
		a.heroManagerLogic = managers.NewHeroManagerLogic(a.entityWrapper.GetHeroManager())
	}
	return a.heroManagerLogic
}
