// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: core.proto

package core

import (
	mme "gitee.com/orbit-w/orbit/pkg/proto/mme"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type Notify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *string                `protobuf:"bytes,1,opt,name=Content,proto3,oneof" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *Book) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type OK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OK) Reset() {
	*x = OK{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OK) ProtoMessage() {}

func (x *OK) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OK.ProtoReflect.Descriptor instead.
func (*OK) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        *string                `protobuf:"bytes,1,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type EntityChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityRef     *mme.EntityRef         `protobuf:"bytes,1,opt,name=EntityRef,proto3,oneof" json:"EntityRef,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3,oneof" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityChange) Reset() {
	*x = EntityChange{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityChange) ProtoMessage() {}

func (x *EntityChange) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityChange.ProtoReflect.Descriptor instead.
func (*EntityChange) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *EntityChange) GetEntityRef() *mme.EntityRef {
	if x != nil {
		return x.EntityRef
	}
	return nil
}

func (x *EntityChange) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Request_HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_HeartBeat) Reset() {
	*x = Request_HeartBeat{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_HeartBeat) ProtoMessage() {}

func (x *Request_HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_HeartBeat.ProtoReflect.Descriptor instead.
func (*Request_HeartBeat) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0, 0}
}

type Request_SetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityRef     *mme.EntityRef         `protobuf:"bytes,1,opt,name=EntityRef,proto3,oneof" json:"EntityRef,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3,oneof" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SetEntityRequest) Reset() {
	*x = Request_SetEntityRequest{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SetEntityRequest) ProtoMessage() {}

func (x *Request_SetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SetEntityRequest.ProtoReflect.Descriptor instead.
func (*Request_SetEntityRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Request_SetEntityRequest) GetEntityRef() *mme.EntityRef {
	if x != nil {
		return x.EntityRef
	}
	return nil
}

func (x *Request_SetEntityRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Notify_BeAttacked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurHp         *int32                 `protobuf:"varint,1,opt,name=CurHp,proto3,oneof" json:"CurHp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify_BeAttacked) Reset() {
	*x = Notify_BeAttacked{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify_BeAttacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_BeAttacked) ProtoMessage() {}

func (x *Notify_BeAttacked) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_BeAttacked.ProtoReflect.Descriptor instead.
func (*Notify_BeAttacked) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Notify_BeAttacked) GetCurHp() int32 {
	if x != nil && x.CurHp != nil {
		return *x.CurHp
	}
	return 0
}

type Notify_EntityChangeNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityChanges []*EntityChange        `protobuf:"bytes,1,rep,name=EntityChanges,proto3" json:"EntityChanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify_EntityChangeNotify) Reset() {
	*x = Notify_EntityChangeNotify{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify_EntityChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_EntityChangeNotify) ProtoMessage() {}

func (x *Notify_EntityChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_EntityChangeNotify.ProtoReflect.Descriptor instead.
func (*Notify_EntityChangeNotify) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Notify_EntityChangeNotify) GetEntityChanges() []*EntityChange {
	if x != nil {
		return x.EntityChanges
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04Core\x1a\fcommon.proto\"\x8d\x01\n" +
	"\aRequest\x1a\v\n" +
	"\tHeartBeat\x1au\n" +
	"\x10SetEntityRequest\x121\n" +
	"\tEntityRef\x18\x01 \x01(\v2\x0e.MME.EntityRefH\x00R\tEntityRef\x88\x01\x01\x12\x17\n" +
	"\x04Data\x18\x02 \x01(\fH\x01R\x04Data\x88\x01\x01B\f\n" +
	"\n" +
	"_EntityRefB\a\n" +
	"\x05_Data\"\x8b\x01\n" +
	"\x06Notify\x1a1\n" +
	"\n" +
	"BeAttacked\x12\x19\n" +
	"\x05CurHp\x18\x01 \x01(\x05H\x00R\x05CurHp\x88\x01\x01B\b\n" +
	"\x06_CurHp\x1aN\n" +
	"\x12EntityChangeNotify\x128\n" +
	"\rEntityChanges\x18\x01 \x03(\v2\x12.Core.EntityChangeR\rEntityChanges\"1\n" +
	"\x04Book\x12\x1d\n" +
	"\aContent\x18\x01 \x01(\tH\x00R\aContent\x88\x01\x01B\n" +
	"\n" +
	"\b_Content\"\x04\n" +
	"\x02OK\"/\n" +
	"\x05Error\x12\x1b\n" +
	"\x06Reason\x18\x01 \x01(\tH\x00R\x06Reason\x88\x01\x01B\t\n" +
	"\a_Reason\"q\n" +
	"\fEntityChange\x121\n" +
	"\tEntityRef\x18\x01 \x01(\v2\x0e.MME.EntityRefH\x00R\tEntityRef\x88\x01\x01\x12\x17\n" +
	"\x04Data\x18\x02 \x01(\fH\x01R\x04Data\x88\x01\x01B\f\n" +
	"\n" +
	"_EntityRefB\a\n" +
	"\x05_DataB(Z&gitee.com/orbit-w/orbit/pkg/proto/coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_proto_goTypes = []any{
	(*Request)(nil),                   // 0: Core.Request
	(*Notify)(nil),                    // 1: Core.Notify
	(*Book)(nil),                      // 2: Core.Book
	(*OK)(nil),                        // 3: Core.OK
	(*Error)(nil),                     // 4: Core.Error
	(*EntityChange)(nil),              // 5: Core.EntityChange
	(*Request_HeartBeat)(nil),         // 6: Core.Request.HeartBeat
	(*Request_SetEntityRequest)(nil),  // 7: Core.Request.SetEntityRequest
	(*Notify_BeAttacked)(nil),         // 8: Core.Notify.BeAttacked
	(*Notify_EntityChangeNotify)(nil), // 9: Core.Notify.EntityChangeNotify
	(*mme.EntityRef)(nil),             // 10: MME.EntityRef
}
var file_core_proto_depIdxs = []int32{
	10, // 0: Core.EntityChange.EntityRef:type_name -> MME.EntityRef
	10, // 1: Core.Request.SetEntityRequest.EntityRef:type_name -> MME.EntityRef
	5,  // 2: Core.Notify.EntityChangeNotify.EntityChanges:type_name -> Core.EntityChange
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_core_proto_msgTypes[2].OneofWrappers = []any{}
	file_core_proto_msgTypes[4].OneofWrappers = []any{}
	file_core_proto_msgTypes[5].OneofWrappers = []any{}
	file_core_proto_msgTypes[7].OneofWrappers = []any{}
	file_core_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
