// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: mme.proto

package mme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_mme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mme_proto_rawDescGZIP(), []int{0}
}

type Notify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_mme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_mme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_mme_proto_rawDescGZIP(), []int{1}
}

type Request_AskLevelUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpNum         *int32                 `protobuf:"varint,1,opt,name=UpNum,proto3,oneof" json:"UpNum,omitempty"`
	Loc           *MMELocation           `protobuf:"bytes,1000,opt,name=Loc,proto3,oneof" json:"Loc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_AskLevelUp) Reset() {
	*x = Request_AskLevelUp{}
	mi := &file_mme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_AskLevelUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_AskLevelUp) ProtoMessage() {}

func (x *Request_AskLevelUp) ProtoReflect() protoreflect.Message {
	mi := &file_mme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_AskLevelUp.ProtoReflect.Descriptor instead.
func (*Request_AskLevelUp) Descriptor() ([]byte, []int) {
	return file_mme_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_AskLevelUp) GetUpNum() int32 {
	if x != nil && x.UpNum != nil {
		return *x.UpNum
	}
	return 0
}

func (x *Request_AskLevelUp) GetLoc() *MMELocation {
	if x != nil {
		return x.Loc
	}
	return nil
}

type Request_AskLevelUp_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *string                `protobuf:"bytes,1,opt,name=Result,proto3,oneof" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_AskLevelUp_Rsp) Reset() {
	*x = Request_AskLevelUp_Rsp{}
	mi := &file_mme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_AskLevelUp_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_AskLevelUp_Rsp) ProtoMessage() {}

func (x *Request_AskLevelUp_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_mme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_AskLevelUp_Rsp.ProtoReflect.Descriptor instead.
func (*Request_AskLevelUp_Rsp) Descriptor() ([]byte, []int) {
	return file_mme_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_AskLevelUp_Rsp) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type Notify_ExpChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exp           *int32                 `protobuf:"varint,1,opt,name=Exp,proto3,oneof" json:"Exp,omitempty"`
	Loc           *MMELocation           `protobuf:"bytes,1000,opt,name=Loc,proto3,oneof" json:"Loc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify_ExpChange) Reset() {
	*x = Notify_ExpChange{}
	mi := &file_mme_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify_ExpChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify_ExpChange) ProtoMessage() {}

func (x *Notify_ExpChange) ProtoReflect() protoreflect.Message {
	mi := &file_mme_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify_ExpChange.ProtoReflect.Descriptor instead.
func (*Notify_ExpChange) Descriptor() ([]byte, []int) {
	return file_mme_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Notify_ExpChange) GetExp() int32 {
	if x != nil && x.Exp != nil {
		return *x.Exp
	}
	return 0
}

func (x *Notify_ExpChange) GetLoc() *MMELocation {
	if x != nil {
		return x.Loc
	}
	return nil
}

var File_mme_proto protoreflect.FileDescriptor

const file_mme_proto_rawDesc = "" +
	"\n" +
	"\tmme.proto\x12\x03MME\x1a\fcommon.proto\"\x9e\x01\n" +
	"\aRequest\x1a\x92\x01\n" +
	"\n" +
	"AskLevelUp\x12\x19\n" +
	"\x05UpNum\x18\x01 \x01(\x05H\x00R\x05UpNum\x88\x01\x01\x12(\n" +
	"\x03Loc\x18\xe8\a \x01(\v2\x10.MME.MMELocationH\x01R\x03Loc\x88\x01\x01\x1a-\n" +
	"\x03Rsp\x12\x1b\n" +
	"\x06Result\x18\x01 \x01(\tH\x00R\x06Result\x88\x01\x01B\t\n" +
	"\a_ResultB\b\n" +
	"\x06_UpNumB\x06\n" +
	"\x04_Loc\"f\n" +
	"\x06Notify\x1a\\\n" +
	"\tExpChange\x12\x15\n" +
	"\x03Exp\x18\x01 \x01(\x05H\x00R\x03Exp\x88\x01\x01\x12(\n" +
	"\x03Loc\x18\xe8\a \x01(\v2\x10.MME.MMELocationH\x01R\x03Loc\x88\x01\x01B\x06\n" +
	"\x04_ExpB\x06\n" +
	"\x04_LocB1Z/gitee.com/orbit-w/orbit/internal/game/proto/mmeb\x06proto3"

var (
	file_mme_proto_rawDescOnce sync.Once
	file_mme_proto_rawDescData []byte
)

func file_mme_proto_rawDescGZIP() []byte {
	file_mme_proto_rawDescOnce.Do(func() {
		file_mme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mme_proto_rawDesc), len(file_mme_proto_rawDesc)))
	})
	return file_mme_proto_rawDescData
}

var file_mme_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mme_proto_goTypes = []any{
	(*Request)(nil),                // 0: MME.Request
	(*Notify)(nil),                 // 1: MME.Notify
	(*Request_AskLevelUp)(nil),     // 2: MME.Request.AskLevelUp
	(*Request_AskLevelUp_Rsp)(nil), // 3: MME.Request.AskLevelUp.Rsp
	(*Notify_ExpChange)(nil),       // 4: MME.Notify.ExpChange
	(*MMELocation)(nil),            // 5: MME.MMELocation
}
var file_mme_proto_depIdxs = []int32{
	5, // 0: MME.Request.AskLevelUp.Loc:type_name -> MME.MMELocation
	5, // 1: MME.Notify.ExpChange.Loc:type_name -> MME.MMELocation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mme_proto_init() }
func file_mme_proto_init() {
	if File_mme_proto != nil {
		return
	}
	file_common_proto_init()
	file_mme_proto_msgTypes[2].OneofWrappers = []any{}
	file_mme_proto_msgTypes[3].OneofWrappers = []any{}
	file_mme_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mme_proto_rawDesc), len(file_mme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mme_proto_goTypes,
		DependencyIndexes: file_mme_proto_depIdxs,
		MessageInfos:      file_mme_proto_msgTypes,
	}.Build()
	File_mme_proto = out.File
	file_mme_proto_goTypes = nil
	file_mme_proto_depIdxs = nil
}
