[server]
name = "orbit-game"
stage = "dev"
host = "127.0.0.1"
port = "8950"

[redis]
addr = ["r-2vc71j95x8xtovlgerpd.redis.cn-chengdu.rds.aliyuncs.com:6379"]
username = "r-2vc71j95x8xtovlger"
password = "Z)cG1v)M9d="
db = 0
cluster = false
max_idle_conns = 20
max_active_conns = 50

[cluster.nacos]
# Nacos 服务器地址列表
server_hosts = ["mse-63a694613-p.nacos-ans.mse.aliyuncs.com"]
# 命名空间ID（可选）
namespace_id = "85a5d5cf-a969-4d61-841d-7a3829f0f28c"
# 服务组名
group_name = "TEST_GROUP"
# 用户名（可选，如果 Nacos 开启了认证）
username = ""
# 密码（可选，如果 Nacos 开启了认证）
password = ""
# 超时时间（毫秒）
timeout_ms = 5000
# 心跳间隔（秒）
beat_interval = 5