// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: sample.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0}
}

type Request_SearchNewsPaper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=Title,proto3,oneof" json:"Title,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,2,opt,name=PageNumber,proto3,oneof" json:"PageNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchNewsPaper) Reset() {
	*x = Request_SearchNewsPaper{}
	mi := &file_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchNewsPaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchNewsPaper) ProtoMessage() {}

func (x *Request_SearchNewsPaper) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchNewsPaper.ProtoReflect.Descriptor instead.
func (*Request_SearchNewsPaper) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_SearchNewsPaper) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Request_SearchNewsPaper) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

type Request_SearchNewsPaper_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *string                `protobuf:"bytes,1,opt,name=Result,proto3,oneof" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_SearchNewsPaper_Rsp) Reset() {
	*x = Request_SearchNewsPaper_Rsp{}
	mi := &file_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_SearchNewsPaper_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SearchNewsPaper_Rsp) ProtoMessage() {}

func (x *Request_SearchNewsPaper_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SearchNewsPaper_Rsp.ProtoReflect.Descriptor instead.
func (*Request_SearchNewsPaper_Rsp) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Request_SearchNewsPaper_Rsp) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

var File_sample_proto protoreflect.FileDescriptor

const file_sample_proto_rawDesc = "" +
	"\n" +
	"\fsample.proto\x12\x06Sample\"\xa5\x01\n" +
	"\aRequest\x1a\x99\x01\n" +
	"\x0fSearchNewsPaper\x12\x19\n" +
	"\x05Title\x18\x01 \x01(\tH\x00R\x05Title\x88\x01\x01\x12#\n" +
	"\n" +
	"PageNumber\x18\x02 \x01(\x05H\x01R\n" +
	"PageNumber\x88\x01\x01\x1a-\n" +
	"\x03Rsp\x12\x1b\n" +
	"\x06Result\x18\x01 \x01(\tH\x00R\x06Result\x88\x01\x01B\t\n" +
	"\a_ResultB\b\n" +
	"\x06_TitleB\r\n" +
	"\v_PageNumberB*Z(gitee.com/orbit-w/orbit/pkg/proto/sampleb\x06proto3"

var (
	file_sample_proto_rawDescOnce sync.Once
	file_sample_proto_rawDescData []byte
)

func file_sample_proto_rawDescGZIP() []byte {
	file_sample_proto_rawDescOnce.Do(func() {
		file_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)))
	})
	return file_sample_proto_rawDescData
}

var file_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sample_proto_goTypes = []any{
	(*Request)(nil),                     // 0: Sample.Request
	(*Request_SearchNewsPaper)(nil),     // 1: Sample.Request.SearchNewsPaper
	(*Request_SearchNewsPaper_Rsp)(nil), // 2: Sample.Request.SearchNewsPaper.Rsp
}
var file_sample_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_proto_init() }
func file_sample_proto_init() {
	if File_sample_proto != nil {
		return
	}
	file_sample_proto_msgTypes[1].OneofWrappers = []any{}
	file_sample_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sample_proto_goTypes,
		DependencyIndexes: file_sample_proto_depIdxs,
		MessageInfos:      file_sample_proto_msgTypes,
	}.Build()
	File_sample_proto = out.File
	file_sample_proto_goTypes = nil
	file_sample_proto_depIdxs = nil
}
