// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: actor_ref.proto

package actor

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatcherType int32

const (
	DispatcherType_DISPATCHER_TYPE_IN_WORLD  DispatcherType = 0 // 世界分组
	DispatcherType_DISPATCHER_TYPE_IN_REGION DispatcherType = 1 // 区域分组
	DispatcherType_DISPATCHER_TYPE_RANDOM    DispatcherType = 2 // 随机分组
)

// Enum value maps for DispatcherType.
var (
	DispatcherType_name = map[int32]string{
		0: "DISPATCHER_TYPE_IN_WORLD",
		1: "DISPATCHER_TYPE_IN_REGION",
		2: "DISPATCHER_TYPE_RANDOM",
	}
	DispatcherType_value = map[string]int32{
		"DISPATCHER_TYPE_IN_WORLD":  0,
		"DISPATCHER_TYPE_IN_REGION": 1,
		"DISPATCHER_TYPE_RANDOM":    2,
	}
)

func (x DispatcherType) Enum() *DispatcherType {
	p := new(DispatcherType)
	*p = x
	return p
}

func (x DispatcherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatcherType) Descriptor() protoreflect.EnumDescriptor {
	return file_actor_ref_proto_enumTypes[0].Descriptor()
}

func (DispatcherType) Type() protoreflect.EnumType {
	return &file_actor_ref_proto_enumTypes[0]
}

func (x DispatcherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatcherType.Descriptor instead.
func (DispatcherType) EnumDescriptor() ([]byte, []int) {
	return file_actor_ref_proto_rawDescGZIP(), []int{0}
}

type ActorRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PID           *actor.PID             `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Dispatcher    *Dispatcher            `protobuf:"bytes,2,opt,name=Dispatcher,proto3" json:"Dispatcher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRef) Reset() {
	*x = ActorRef{}
	mi := &file_actor_ref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRef) ProtoMessage() {}

func (x *ActorRef) ProtoReflect() protoreflect.Message {
	mi := &file_actor_ref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRef.ProtoReflect.Descriptor instead.
func (*ActorRef) Descriptor() ([]byte, []int) {
	return file_actor_ref_proto_rawDescGZIP(), []int{0}
}

func (x *ActorRef) GetPID() *actor.PID {
	if x != nil {
		return x.PID
	}
	return nil
}

func (x *ActorRef) GetDispatcher() *Dispatcher {
	if x != nil {
		return x.Dispatcher
	}
	return nil
}

type Dispatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DispatcherType         `protobuf:"varint,1,opt,name=Type,proto3,enum=actor.DispatcherType" json:"Type,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=WorldId,proto3" json:"WorldId,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dispatcher) Reset() {
	*x = Dispatcher{}
	mi := &file_actor_ref_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatcher) ProtoMessage() {}

func (x *Dispatcher) ProtoReflect() protoreflect.Message {
	mi := &file_actor_ref_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatcher.ProtoReflect.Descriptor instead.
func (*Dispatcher) Descriptor() ([]byte, []int) {
	return file_actor_ref_proto_rawDescGZIP(), []int{1}
}

func (x *Dispatcher) GetType() DispatcherType {
	if x != nil {
		return x.Type
	}
	return DispatcherType_DISPATCHER_TYPE_IN_WORLD
}

func (x *Dispatcher) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *Dispatcher) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_actor_ref_proto protoreflect.FileDescriptor

var file_actor_ref_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x0b, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x66, 0x12, 0x1c, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12,
	0x31, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x70,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x52, 0x0a, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x22, 0x69, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x12, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x2a, 0x69, 0x0a,
	0x0e, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x18, 0x44, 0x49, 0x53, 0x50, 0x41, 0x54, 0x43, 0x48, 0x45, 0x52, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x57, 0x4f, 0x52, 0x4c, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a,
	0x19, 0x44, 0x49, 0x53, 0x50, 0x41, 0x54, 0x43, 0x48, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16,
	0x44, 0x49, 0x53, 0x50, 0x41, 0x54, 0x43, 0x48, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_actor_ref_proto_rawDescOnce sync.Once
	file_actor_ref_proto_rawDescData []byte
)

func file_actor_ref_proto_rawDescGZIP() []byte {
	file_actor_ref_proto_rawDescOnce.Do(func() {
		file_actor_ref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_ref_proto_rawDesc), len(file_actor_ref_proto_rawDesc)))
	})
	return file_actor_ref_proto_rawDescData
}

var file_actor_ref_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_actor_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_actor_ref_proto_goTypes = []any{
	(DispatcherType)(0), // 0: actor.DispatcherType
	(*ActorRef)(nil),    // 1: actor.ActorRef
	(*Dispatcher)(nil),  // 2: actor.Dispatcher
	(*actor.PID)(nil),   // 3: actor.PID
}
var file_actor_ref_proto_depIdxs = []int32{
	3, // 0: actor.ActorRef.PID:type_name -> actor.PID
	2, // 1: actor.ActorRef.Dispatcher:type_name -> actor.Dispatcher
	0, // 2: actor.Dispatcher.Type:type_name -> actor.DispatcherType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_actor_ref_proto_init() }
func file_actor_ref_proto_init() {
	if File_actor_ref_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_ref_proto_rawDesc), len(file_actor_ref_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_ref_proto_goTypes,
		DependencyIndexes: file_actor_ref_proto_depIdxs,
		EnumInfos:         file_actor_ref_proto_enumTypes,
		MessageInfos:      file_actor_ref_proto_msgTypes,
	}.Build()
	File_actor_ref_proto = out.File
	file_actor_ref_proto_goTypes = nil
	file_actor_ref_proto_depIdxs = nil
}
